services:
  server:
    container_name: feeblo-server
    image: ghcr.io/g3root/feeblo-server:${IMAGE_TAG:-nightly}
    restart: always
    environment:
      NODE_ENV: production
      PORT: ${SERVER_PORT:-8080}
      SERVER_PORT: ${SERVER_PORT:-8080}
      PUBLIC_APP_URL: ${PUBLIC_APP_URL}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
      PUBLIC_APP_RELEASE: ${IMAGE_TAG:-nightly}
    ports:
      - "${SERVER_PORT:-8080}:8080"

  web:
    container_name: feeblo-web
    image: ghcr.io/g3root/feeblo-web:${IMAGE_TAG:-nightly}
    restart: always
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: ${WEB_PORT:-4321}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
      PUBLIC_APP_URL: ${PUBLIC_APP_URL}
      PUBLIC_APP_ROOT_DOMAIN: ${PUBLIC_APP_ROOT_DOMAIN}
      PUBLIC_APP_RELEASE: ${IMAGE_TAG:-nightly}
    ports:
      - "${WEB_PORT:-4321}:4321"
    depends_on:
      - server
