// This file is generated by icon spritesheet generator

export const iconNames = [
  "ArrowLeft01Icon",
  "Cancel01Icon",
  "CheckIcon",
  "SentIcon",
] as const

export type IconName = typeof iconNames[number]
