/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as DashboardRouteImport } from "./routes/_dashboard"
import { Route as RobotsDottxtRouteImport } from "./routes/robots[.]txt"
import { Route as DashboardSplatRouteImport } from "./routes/_dashboard/$"
import { Route as DashboardOrganizationIdRouteImport } from "./routes/_dashboard/$organizationId"
import { Route as DashboardEmailVerifyRouteImport } from "./routes/_dashboard/email-verify"
import { Route as DashboardForgotPasswordRouteImport } from "./routes/_dashboard/forgot-password"
import { Route as DashboardRegisterRouteImport } from "./routes/_dashboard/register"
import { Route as DashboardResetPasswordRouteImport } from "./routes/_dashboard/reset-password"
import { Route as DashboardSignInRouteImport } from "./routes/_dashboard/sign-in"
import { Route as DashboardSignUpRouteImport } from "./routes/_dashboard/sign-up"
import { Route as FeedbackWidgetOrganizationIdRouteImport } from "./routes/feedback-widget/$organizationId"
import { Route as SSplatRouteImport } from "./routes/s/$"
import { Route as SRobotsDottxtRouteImport } from "./routes/s/robots[.]txt"
import { Route as SSitemapDotxmlRouteImport } from "./routes/s/sitemap[.]xml"
import { Route as DashboardOrganizationIdDashboardLayoutRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout"
import { Route as DashboardOrganizationIdSettingsRouteImport } from "./routes/_dashboard/$organizationId/settings"
import { Route as SChangelogRssDotxmlRouteImport } from "./routes/s/changelog/rss[.]xml"
import { Route as DashboardOrganizationIdDashboardLayoutIndexRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/index"
import { Route as DashboardOrganizationIdSettingsIndexRouteImport } from "./routes/_dashboard/$organizationId/settings/index"
import { Route as DashboardOrganizationIdSettingsBillingRouteImport } from "./routes/_dashboard/$organizationId/settings/billing"
import { Route as DashboardOrganizationIdSettingsChangelogCategoriesRouteImport } from "./routes/_dashboard/$organizationId/settings/changelog-categories"
import { Route as DashboardOrganizationIdSettingsChangelogPrivacyRouteImport } from "./routes/_dashboard/$organizationId/settings/changelog-privacy"
import { Route as DashboardOrganizationIdSettingsCustomAttributesRouteImport } from "./routes/_dashboard/$organizationId/settings/custom-attributes"
import { Route as DashboardOrganizationIdSettingsCustomizeRouteImport } from "./routes/_dashboard/$organizationId/settings/customize"
import { Route as DashboardOrganizationIdSettingsFeedbackTagsRouteImport } from "./routes/_dashboard/$organizationId/settings/feedback-tags"
import { Route as DashboardOrganizationIdSettingsMembersRouteImport } from "./routes/_dashboard/$organizationId/settings/members"
import { Route as DashboardOrganizationIdSettingsPreferencesRouteImport } from "./routes/_dashboard/$organizationId/settings/preferences"
import { Route as DashboardOrganizationIdSettingsProfileRouteImport } from "./routes/_dashboard/$organizationId/settings/profile"
import { Route as DashboardOrganizationIdSettingsRoadmapRouteImport } from "./routes/_dashboard/$organizationId/settings/roadmap"
import { Route as DashboardOrganizationIdSettingsSecurityRouteImport } from "./routes/_dashboard/$organizationId/settings/security"
import { Route as DashboardOrganizationIdSettingsWorkspaceRouteImport } from "./routes/_dashboard/$organizationId/settings/workspace"
import { Route as DashboardOrganizationIdDashboardLayoutChangelogIndexRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/changelog/index"
import { Route as DashboardOrganizationIdDashboardLayoutChangelogDraftRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/changelog/draft"
import { Route as DashboardOrganizationIdDashboardLayoutChangelogPublishedRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/changelog/published"
import { Route as DashboardOrganizationIdDashboardLayoutCompanyIndexRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/company/index"
import { Route as DashboardOrganizationIdDashboardLayoutContactIndexRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/contact/index"
import { Route as DashboardOrganizationIdDashboardLayoutFeedbackIndexRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/feedback/index"
import { Route as DashboardOrganizationIdDashboardLayoutFeedbackActiveRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/feedback/active"
import { Route as DashboardOrganizationIdDashboardLayoutFeedbackBacklogRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/feedback/backlog"
import { Route as DashboardOrganizationIdDashboardLayoutRoadmapIndexRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/roadmap/index"
import { Route as DashboardOrganizationIdDashboardLayoutRoadmapSlugRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/roadmap/$slug"
import { Route as DashboardOrganizationIdSettingsIntegrationsIndexRouteImport } from "./routes/_dashboard/$organizationId/settings/integrations/index"
import { Route as DashboardOrganizationIdSettingsWebhooksIndexRouteImport } from "./routes/_dashboard/$organizationId/settings/webhooks/index"
import { Route as DashboardOrganizationIdSettingsWebhooksConnectionIdRouteImport } from "./routes/_dashboard/$organizationId/settings/webhooks/$connectionId"
import { Route as DashboardOrganizationIdDashboardLayoutBoardBoardSlugIndexRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/index"
import { Route as DashboardOrganizationIdDashboardLayoutBoardBoardSlugActiveRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/active"
import { Route as DashboardOrganizationIdDashboardLayoutBoardBoardSlugBacklogRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/backlog"
import { Route as DashboardOrganizationIdDashboardLayoutChangelogEditChangelogSlugRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/changelog/edit/$changelogSlug"
import { Route as DashboardOrganizationIdDashboardLayoutPostBoardSlugPostSlugRouteImport } from "./routes/_dashboard/$organizationId/_dashboard-layout/post/$boardSlug/$postSlug"
import { Route as DashboardOrganizationIdSettingsIntegrationsDiscordIndexRouteImport } from "./routes/_dashboard/$organizationId/settings/integrations/discord/index"
import { Route as DashboardOrganizationIdSettingsIntegrationsGithubIndexRouteImport } from "./routes/_dashboard/$organizationId/settings/integrations/github/index"
import { Route as DashboardOrganizationIdSettingsIntegrationsSlackIndexRouteImport } from "./routes/_dashboard/$organizationId/settings/integrations/slack/index"

const DashboardRoute = DashboardRouteImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: "/robots.txt",
  path: "/robots.txt",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSplatRoute = DashboardSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrganizationIdRoute = DashboardOrganizationIdRouteImport.update({
  id: "/$organizationId",
  path: "/$organizationId",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailVerifyRoute = DashboardEmailVerifyRouteImport.update({
  id: "/email-verify",
  path: "/email-verify",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForgotPasswordRoute = DashboardForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegisterRoute = DashboardRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResetPasswordRoute = DashboardResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSignInRoute = DashboardSignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSignUpRoute = DashboardSignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => DashboardRoute,
} as any)
const FeedbackWidgetOrganizationIdRoute =
  FeedbackWidgetOrganizationIdRouteImport.update({
    id: "/feedback-widget/$organizationId",
    path: "/feedback-widget/$organizationId",
    getParentRoute: () => rootRouteImport,
  } as any)
const SSplatRoute = SSplatRouteImport.update({
  id: "/s/$",
  path: "/s/$",
  getParentRoute: () => rootRouteImport,
} as any)
const SRobotsDottxtRoute = SRobotsDottxtRouteImport.update({
  id: "/s/robots.txt",
  path: "/s/robots.txt",
  getParentRoute: () => rootRouteImport,
} as any)
const SSitemapDotxmlRoute = SSitemapDotxmlRouteImport.update({
  id: "/s/sitemap.xml",
  path: "/s/sitemap.xml",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrganizationIdDashboardLayoutRoute =
  DashboardOrganizationIdDashboardLayoutRouteImport.update({
    id: "/_dashboard-layout",
    getParentRoute: () => DashboardOrganizationIdRoute,
  } as any)
const DashboardOrganizationIdSettingsRoute =
  DashboardOrganizationIdSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => DashboardOrganizationIdRoute,
  } as any)
const SChangelogRssDotxmlRoute = SChangelogRssDotxmlRouteImport.update({
  id: "/s/changelog/rss.xml",
  path: "/s/changelog/rss.xml",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrganizationIdDashboardLayoutIndexRoute =
  DashboardOrganizationIdDashboardLayoutIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdSettingsIndexRoute =
  DashboardOrganizationIdSettingsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsBillingRoute =
  DashboardOrganizationIdSettingsBillingRouteImport.update({
    id: "/billing",
    path: "/billing",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsChangelogCategoriesRoute =
  DashboardOrganizationIdSettingsChangelogCategoriesRouteImport.update({
    id: "/changelog-categories",
    path: "/changelog-categories",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsChangelogPrivacyRoute =
  DashboardOrganizationIdSettingsChangelogPrivacyRouteImport.update({
    id: "/changelog-privacy",
    path: "/changelog-privacy",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsCustomAttributesRoute =
  DashboardOrganizationIdSettingsCustomAttributesRouteImport.update({
    id: "/custom-attributes",
    path: "/custom-attributes",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsCustomizeRoute =
  DashboardOrganizationIdSettingsCustomizeRouteImport.update({
    id: "/customize",
    path: "/customize",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsFeedbackTagsRoute =
  DashboardOrganizationIdSettingsFeedbackTagsRouteImport.update({
    id: "/feedback-tags",
    path: "/feedback-tags",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsMembersRoute =
  DashboardOrganizationIdSettingsMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsPreferencesRoute =
  DashboardOrganizationIdSettingsPreferencesRouteImport.update({
    id: "/preferences",
    path: "/preferences",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsProfileRoute =
  DashboardOrganizationIdSettingsProfileRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsRoadmapRoute =
  DashboardOrganizationIdSettingsRoadmapRouteImport.update({
    id: "/roadmap",
    path: "/roadmap",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsSecurityRoute =
  DashboardOrganizationIdSettingsSecurityRouteImport.update({
    id: "/security",
    path: "/security",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsWorkspaceRoute =
  DashboardOrganizationIdSettingsWorkspaceRouteImport.update({
    id: "/workspace",
    path: "/workspace",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutChangelogIndexRoute =
  DashboardOrganizationIdDashboardLayoutChangelogIndexRouteImport.update({
    id: "/changelog/",
    path: "/changelog/",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutChangelogDraftRoute =
  DashboardOrganizationIdDashboardLayoutChangelogDraftRouteImport.update({
    id: "/changelog/draft",
    path: "/changelog/draft",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutChangelogPublishedRoute =
  DashboardOrganizationIdDashboardLayoutChangelogPublishedRouteImport.update({
    id: "/changelog/published",
    path: "/changelog/published",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutCompanyIndexRoute =
  DashboardOrganizationIdDashboardLayoutCompanyIndexRouteImport.update({
    id: "/company/",
    path: "/company/",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutContactIndexRoute =
  DashboardOrganizationIdDashboardLayoutContactIndexRouteImport.update({
    id: "/contact/",
    path: "/contact/",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutFeedbackIndexRoute =
  DashboardOrganizationIdDashboardLayoutFeedbackIndexRouteImport.update({
    id: "/feedback/",
    path: "/feedback/",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutFeedbackActiveRoute =
  DashboardOrganizationIdDashboardLayoutFeedbackActiveRouteImport.update({
    id: "/feedback/active",
    path: "/feedback/active",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutFeedbackBacklogRoute =
  DashboardOrganizationIdDashboardLayoutFeedbackBacklogRouteImport.update({
    id: "/feedback/backlog",
    path: "/feedback/backlog",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutRoadmapIndexRoute =
  DashboardOrganizationIdDashboardLayoutRoadmapIndexRouteImport.update({
    id: "/roadmap/",
    path: "/roadmap/",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutRoadmapSlugRoute =
  DashboardOrganizationIdDashboardLayoutRoadmapSlugRouteImport.update({
    id: "/roadmap/$slug",
    path: "/roadmap/$slug",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdSettingsIntegrationsIndexRoute =
  DashboardOrganizationIdSettingsIntegrationsIndexRouteImport.update({
    id: "/integrations/",
    path: "/integrations/",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsWebhooksIndexRoute =
  DashboardOrganizationIdSettingsWebhooksIndexRouteImport.update({
    id: "/webhooks/",
    path: "/webhooks/",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsWebhooksConnectionIdRoute =
  DashboardOrganizationIdSettingsWebhooksConnectionIdRouteImport.update({
    id: "/webhooks/$connectionId",
    path: "/webhooks/$connectionId",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutBoardBoardSlugIndexRoute =
  DashboardOrganizationIdDashboardLayoutBoardBoardSlugIndexRouteImport.update({
    id: "/board/$boardSlug/",
    path: "/board/$boardSlug/",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutBoardBoardSlugActiveRoute =
  DashboardOrganizationIdDashboardLayoutBoardBoardSlugActiveRouteImport.update({
    id: "/board/$boardSlug/active",
    path: "/board/$boardSlug/active",
    getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
  } as any)
const DashboardOrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute =
  DashboardOrganizationIdDashboardLayoutBoardBoardSlugBacklogRouteImport.update(
    {
      id: "/board/$boardSlug/backlog",
      path: "/board/$boardSlug/backlog",
      getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
    } as any,
  )
const DashboardOrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute =
  DashboardOrganizationIdDashboardLayoutChangelogEditChangelogSlugRouteImport.update(
    {
      id: "/changelog/edit/$changelogSlug",
      path: "/changelog/edit/$changelogSlug",
      getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
    } as any,
  )
const DashboardOrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute =
  DashboardOrganizationIdDashboardLayoutPostBoardSlugPostSlugRouteImport.update(
    {
      id: "/post/$boardSlug/$postSlug",
      path: "/post/$boardSlug/$postSlug",
      getParentRoute: () => DashboardOrganizationIdDashboardLayoutRoute,
    } as any,
  )
const DashboardOrganizationIdSettingsIntegrationsDiscordIndexRoute =
  DashboardOrganizationIdSettingsIntegrationsDiscordIndexRouteImport.update({
    id: "/integrations/discord/",
    path: "/integrations/discord/",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsIntegrationsGithubIndexRoute =
  DashboardOrganizationIdSettingsIntegrationsGithubIndexRouteImport.update({
    id: "/integrations/github/",
    path: "/integrations/github/",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)
const DashboardOrganizationIdSettingsIntegrationsSlackIndexRoute =
  DashboardOrganizationIdSettingsIntegrationsSlackIndexRouteImport.update({
    id: "/integrations/slack/",
    path: "/integrations/slack/",
    getParentRoute: () => DashboardOrganizationIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof DashboardRouteWithChildren
  "/robots.txt": typeof RobotsDottxtRoute
  "/$": typeof DashboardSplatRoute
  "/$organizationId": typeof DashboardOrganizationIdRouteWithChildren
  "/email-verify": typeof DashboardEmailVerifyRoute
  "/forgot-password": typeof DashboardForgotPasswordRoute
  "/register": typeof DashboardRegisterRoute
  "/reset-password": typeof DashboardResetPasswordRoute
  "/sign-in": typeof DashboardSignInRoute
  "/sign-up": typeof DashboardSignUpRoute
  "/feedback-widget/$organizationId": typeof FeedbackWidgetOrganizationIdRoute
  "/s/$": typeof SSplatRoute
  "/s/robots.txt": typeof SRobotsDottxtRoute
  "/s/sitemap.xml": typeof SSitemapDotxmlRoute
  "/$organizationId/settings": typeof DashboardOrganizationIdSettingsRouteWithChildren
  "/s/changelog/rss.xml": typeof SChangelogRssDotxmlRoute
  "/$organizationId/settings/billing": typeof DashboardOrganizationIdSettingsBillingRoute
  "/$organizationId/settings/changelog-categories": typeof DashboardOrganizationIdSettingsChangelogCategoriesRoute
  "/$organizationId/settings/changelog-privacy": typeof DashboardOrganizationIdSettingsChangelogPrivacyRoute
  "/$organizationId/settings/custom-attributes": typeof DashboardOrganizationIdSettingsCustomAttributesRoute
  "/$organizationId/settings/customize": typeof DashboardOrganizationIdSettingsCustomizeRoute
  "/$organizationId/settings/feedback-tags": typeof DashboardOrganizationIdSettingsFeedbackTagsRoute
  "/$organizationId/settings/members": typeof DashboardOrganizationIdSettingsMembersRoute
  "/$organizationId/settings/preferences": typeof DashboardOrganizationIdSettingsPreferencesRoute
  "/$organizationId/settings/profile": typeof DashboardOrganizationIdSettingsProfileRoute
  "/$organizationId/settings/roadmap": typeof DashboardOrganizationIdSettingsRoadmapRoute
  "/$organizationId/settings/security": typeof DashboardOrganizationIdSettingsSecurityRoute
  "/$organizationId/settings/workspace": typeof DashboardOrganizationIdSettingsWorkspaceRoute
  "/$organizationId/": typeof DashboardOrganizationIdDashboardLayoutIndexRoute
  "/$organizationId/settings/": typeof DashboardOrganizationIdSettingsIndexRoute
  "/$organizationId/changelog/draft": typeof DashboardOrganizationIdDashboardLayoutChangelogDraftRoute
  "/$organizationId/changelog/published": typeof DashboardOrganizationIdDashboardLayoutChangelogPublishedRoute
  "/$organizationId/feedback/active": typeof DashboardOrganizationIdDashboardLayoutFeedbackActiveRoute
  "/$organizationId/feedback/backlog": typeof DashboardOrganizationIdDashboardLayoutFeedbackBacklogRoute
  "/$organizationId/roadmap/$slug": typeof DashboardOrganizationIdDashboardLayoutRoadmapSlugRoute
  "/$organizationId/settings/webhooks/$connectionId": typeof DashboardOrganizationIdSettingsWebhooksConnectionIdRoute
  "/$organizationId/changelog/": typeof DashboardOrganizationIdDashboardLayoutChangelogIndexRoute
  "/$organizationId/company/": typeof DashboardOrganizationIdDashboardLayoutCompanyIndexRoute
  "/$organizationId/contact/": typeof DashboardOrganizationIdDashboardLayoutContactIndexRoute
  "/$organizationId/feedback/": typeof DashboardOrganizationIdDashboardLayoutFeedbackIndexRoute
  "/$organizationId/roadmap/": typeof DashboardOrganizationIdDashboardLayoutRoadmapIndexRoute
  "/$organizationId/settings/integrations/": typeof DashboardOrganizationIdSettingsIntegrationsIndexRoute
  "/$organizationId/settings/webhooks/": typeof DashboardOrganizationIdSettingsWebhooksIndexRoute
  "/$organizationId/board/$boardSlug/active": typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugActiveRoute
  "/$organizationId/board/$boardSlug/backlog": typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute
  "/$organizationId/changelog/edit/$changelogSlug": typeof DashboardOrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute
  "/$organizationId/post/$boardSlug/$postSlug": typeof DashboardOrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute
  "/$organizationId/board/$boardSlug/": typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugIndexRoute
  "/$organizationId/settings/integrations/discord/": typeof DashboardOrganizationIdSettingsIntegrationsDiscordIndexRoute
  "/$organizationId/settings/integrations/github/": typeof DashboardOrganizationIdSettingsIntegrationsGithubIndexRoute
  "/$organizationId/settings/integrations/slack/": typeof DashboardOrganizationIdSettingsIntegrationsSlackIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof DashboardRouteWithChildren
  "/robots.txt": typeof RobotsDottxtRoute
  "/$": typeof DashboardSplatRoute
  "/$organizationId": typeof DashboardOrganizationIdDashboardLayoutIndexRoute
  "/email-verify": typeof DashboardEmailVerifyRoute
  "/forgot-password": typeof DashboardForgotPasswordRoute
  "/register": typeof DashboardRegisterRoute
  "/reset-password": typeof DashboardResetPasswordRoute
  "/sign-in": typeof DashboardSignInRoute
  "/sign-up": typeof DashboardSignUpRoute
  "/feedback-widget/$organizationId": typeof FeedbackWidgetOrganizationIdRoute
  "/s/$": typeof SSplatRoute
  "/s/robots.txt": typeof SRobotsDottxtRoute
  "/s/sitemap.xml": typeof SSitemapDotxmlRoute
  "/s/changelog/rss.xml": typeof SChangelogRssDotxmlRoute
  "/$organizationId/settings/billing": typeof DashboardOrganizationIdSettingsBillingRoute
  "/$organizationId/settings/changelog-categories": typeof DashboardOrganizationIdSettingsChangelogCategoriesRoute
  "/$organizationId/settings/changelog-privacy": typeof DashboardOrganizationIdSettingsChangelogPrivacyRoute
  "/$organizationId/settings/custom-attributes": typeof DashboardOrganizationIdSettingsCustomAttributesRoute
  "/$organizationId/settings/customize": typeof DashboardOrganizationIdSettingsCustomizeRoute
  "/$organizationId/settings/feedback-tags": typeof DashboardOrganizationIdSettingsFeedbackTagsRoute
  "/$organizationId/settings/members": typeof DashboardOrganizationIdSettingsMembersRoute
  "/$organizationId/settings/preferences": typeof DashboardOrganizationIdSettingsPreferencesRoute
  "/$organizationId/settings/profile": typeof DashboardOrganizationIdSettingsProfileRoute
  "/$organizationId/settings/roadmap": typeof DashboardOrganizationIdSettingsRoadmapRoute
  "/$organizationId/settings/security": typeof DashboardOrganizationIdSettingsSecurityRoute
  "/$organizationId/settings/workspace": typeof DashboardOrganizationIdSettingsWorkspaceRoute
  "/$organizationId/settings": typeof DashboardOrganizationIdSettingsIndexRoute
  "/$organizationId/changelog/draft": typeof DashboardOrganizationIdDashboardLayoutChangelogDraftRoute
  "/$organizationId/changelog/published": typeof DashboardOrganizationIdDashboardLayoutChangelogPublishedRoute
  "/$organizationId/feedback/active": typeof DashboardOrganizationIdDashboardLayoutFeedbackActiveRoute
  "/$organizationId/feedback/backlog": typeof DashboardOrganizationIdDashboardLayoutFeedbackBacklogRoute
  "/$organizationId/roadmap/$slug": typeof DashboardOrganizationIdDashboardLayoutRoadmapSlugRoute
  "/$organizationId/settings/webhooks/$connectionId": typeof DashboardOrganizationIdSettingsWebhooksConnectionIdRoute
  "/$organizationId/changelog": typeof DashboardOrganizationIdDashboardLayoutChangelogIndexRoute
  "/$organizationId/company": typeof DashboardOrganizationIdDashboardLayoutCompanyIndexRoute
  "/$organizationId/contact": typeof DashboardOrganizationIdDashboardLayoutContactIndexRoute
  "/$organizationId/feedback": typeof DashboardOrganizationIdDashboardLayoutFeedbackIndexRoute
  "/$organizationId/roadmap": typeof DashboardOrganizationIdDashboardLayoutRoadmapIndexRoute
  "/$organizationId/settings/integrations": typeof DashboardOrganizationIdSettingsIntegrationsIndexRoute
  "/$organizationId/settings/webhooks": typeof DashboardOrganizationIdSettingsWebhooksIndexRoute
  "/$organizationId/board/$boardSlug/active": typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugActiveRoute
  "/$organizationId/board/$boardSlug/backlog": typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute
  "/$organizationId/changelog/edit/$changelogSlug": typeof DashboardOrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute
  "/$organizationId/post/$boardSlug/$postSlug": typeof DashboardOrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute
  "/$organizationId/board/$boardSlug": typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugIndexRoute
  "/$organizationId/settings/integrations/discord": typeof DashboardOrganizationIdSettingsIntegrationsDiscordIndexRoute
  "/$organizationId/settings/integrations/github": typeof DashboardOrganizationIdSettingsIntegrationsGithubIndexRoute
  "/$organizationId/settings/integrations/slack": typeof DashboardOrganizationIdSettingsIntegrationsSlackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_dashboard": typeof DashboardRouteWithChildren
  "/robots.txt": typeof RobotsDottxtRoute
  "/_dashboard/$": typeof DashboardSplatRoute
  "/_dashboard/$organizationId": typeof DashboardOrganizationIdRouteWithChildren
  "/_dashboard/email-verify": typeof DashboardEmailVerifyRoute
  "/_dashboard/forgot-password": typeof DashboardForgotPasswordRoute
  "/_dashboard/register": typeof DashboardRegisterRoute
  "/_dashboard/reset-password": typeof DashboardResetPasswordRoute
  "/_dashboard/sign-in": typeof DashboardSignInRoute
  "/_dashboard/sign-up": typeof DashboardSignUpRoute
  "/feedback-widget/$organizationId": typeof FeedbackWidgetOrganizationIdRoute
  "/s/$": typeof SSplatRoute
  "/s/robots.txt": typeof SRobotsDottxtRoute
  "/s/sitemap.xml": typeof SSitemapDotxmlRoute
  "/_dashboard/$organizationId/_dashboard-layout": typeof DashboardOrganizationIdDashboardLayoutRouteWithChildren
  "/_dashboard/$organizationId/settings": typeof DashboardOrganizationIdSettingsRouteWithChildren
  "/s/changelog/rss.xml": typeof SChangelogRssDotxmlRoute
  "/_dashboard/$organizationId/settings/billing": typeof DashboardOrganizationIdSettingsBillingRoute
  "/_dashboard/$organizationId/settings/changelog-categories": typeof DashboardOrganizationIdSettingsChangelogCategoriesRoute
  "/_dashboard/$organizationId/settings/changelog-privacy": typeof DashboardOrganizationIdSettingsChangelogPrivacyRoute
  "/_dashboard/$organizationId/settings/custom-attributes": typeof DashboardOrganizationIdSettingsCustomAttributesRoute
  "/_dashboard/$organizationId/settings/customize": typeof DashboardOrganizationIdSettingsCustomizeRoute
  "/_dashboard/$organizationId/settings/feedback-tags": typeof DashboardOrganizationIdSettingsFeedbackTagsRoute
  "/_dashboard/$organizationId/settings/members": typeof DashboardOrganizationIdSettingsMembersRoute
  "/_dashboard/$organizationId/settings/preferences": typeof DashboardOrganizationIdSettingsPreferencesRoute
  "/_dashboard/$organizationId/settings/profile": typeof DashboardOrganizationIdSettingsProfileRoute
  "/_dashboard/$organizationId/settings/roadmap": typeof DashboardOrganizationIdSettingsRoadmapRoute
  "/_dashboard/$organizationId/settings/security": typeof DashboardOrganizationIdSettingsSecurityRoute
  "/_dashboard/$organizationId/settings/workspace": typeof DashboardOrganizationIdSettingsWorkspaceRoute
  "/_dashboard/$organizationId/_dashboard-layout/": typeof DashboardOrganizationIdDashboardLayoutIndexRoute
  "/_dashboard/$organizationId/settings/": typeof DashboardOrganizationIdSettingsIndexRoute
  "/_dashboard/$organizationId/_dashboard-layout/changelog/draft": typeof DashboardOrganizationIdDashboardLayoutChangelogDraftRoute
  "/_dashboard/$organizationId/_dashboard-layout/changelog/published": typeof DashboardOrganizationIdDashboardLayoutChangelogPublishedRoute
  "/_dashboard/$organizationId/_dashboard-layout/feedback/active": typeof DashboardOrganizationIdDashboardLayoutFeedbackActiveRoute
  "/_dashboard/$organizationId/_dashboard-layout/feedback/backlog": typeof DashboardOrganizationIdDashboardLayoutFeedbackBacklogRoute
  "/_dashboard/$organizationId/_dashboard-layout/roadmap/$slug": typeof DashboardOrganizationIdDashboardLayoutRoadmapSlugRoute
  "/_dashboard/$organizationId/settings/webhooks/$connectionId": typeof DashboardOrganizationIdSettingsWebhooksConnectionIdRoute
  "/_dashboard/$organizationId/_dashboard-layout/changelog/": typeof DashboardOrganizationIdDashboardLayoutChangelogIndexRoute
  "/_dashboard/$organizationId/_dashboard-layout/company/": typeof DashboardOrganizationIdDashboardLayoutCompanyIndexRoute
  "/_dashboard/$organizationId/_dashboard-layout/contact/": typeof DashboardOrganizationIdDashboardLayoutContactIndexRoute
  "/_dashboard/$organizationId/_dashboard-layout/feedback/": typeof DashboardOrganizationIdDashboardLayoutFeedbackIndexRoute
  "/_dashboard/$organizationId/_dashboard-layout/roadmap/": typeof DashboardOrganizationIdDashboardLayoutRoadmapIndexRoute
  "/_dashboard/$organizationId/settings/integrations/": typeof DashboardOrganizationIdSettingsIntegrationsIndexRoute
  "/_dashboard/$organizationId/settings/webhooks/": typeof DashboardOrganizationIdSettingsWebhooksIndexRoute
  "/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/active": typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugActiveRoute
  "/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/backlog": typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute
  "/_dashboard/$organizationId/_dashboard-layout/changelog/edit/$changelogSlug": typeof DashboardOrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute
  "/_dashboard/$organizationId/_dashboard-layout/post/$boardSlug/$postSlug": typeof DashboardOrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute
  "/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/": typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugIndexRoute
  "/_dashboard/$organizationId/settings/integrations/discord/": typeof DashboardOrganizationIdSettingsIntegrationsDiscordIndexRoute
  "/_dashboard/$organizationId/settings/integrations/github/": typeof DashboardOrganizationIdSettingsIntegrationsGithubIndexRoute
  "/_dashboard/$organizationId/settings/integrations/slack/": typeof DashboardOrganizationIdSettingsIntegrationsSlackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/robots.txt"
    | "/$"
    | "/$organizationId"
    | "/email-verify"
    | "/forgot-password"
    | "/register"
    | "/reset-password"
    | "/sign-in"
    | "/sign-up"
    | "/feedback-widget/$organizationId"
    | "/s/$"
    | "/s/robots.txt"
    | "/s/sitemap.xml"
    | "/$organizationId/settings"
    | "/s/changelog/rss.xml"
    | "/$organizationId/settings/billing"
    | "/$organizationId/settings/changelog-categories"
    | "/$organizationId/settings/changelog-privacy"
    | "/$organizationId/settings/custom-attributes"
    | "/$organizationId/settings/customize"
    | "/$organizationId/settings/feedback-tags"
    | "/$organizationId/settings/members"
    | "/$organizationId/settings/preferences"
    | "/$organizationId/settings/profile"
    | "/$organizationId/settings/roadmap"
    | "/$organizationId/settings/security"
    | "/$organizationId/settings/workspace"
    | "/$organizationId/"
    | "/$organizationId/settings/"
    | "/$organizationId/changelog/draft"
    | "/$organizationId/changelog/published"
    | "/$organizationId/feedback/active"
    | "/$organizationId/feedback/backlog"
    | "/$organizationId/roadmap/$slug"
    | "/$organizationId/settings/webhooks/$connectionId"
    | "/$organizationId/changelog/"
    | "/$organizationId/company/"
    | "/$organizationId/contact/"
    | "/$organizationId/feedback/"
    | "/$organizationId/roadmap/"
    | "/$organizationId/settings/integrations/"
    | "/$organizationId/settings/webhooks/"
    | "/$organizationId/board/$boardSlug/active"
    | "/$organizationId/board/$boardSlug/backlog"
    | "/$organizationId/changelog/edit/$changelogSlug"
    | "/$organizationId/post/$boardSlug/$postSlug"
    | "/$organizationId/board/$boardSlug/"
    | "/$organizationId/settings/integrations/discord/"
    | "/$organizationId/settings/integrations/github/"
    | "/$organizationId/settings/integrations/slack/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/robots.txt"
    | "/$"
    | "/$organizationId"
    | "/email-verify"
    | "/forgot-password"
    | "/register"
    | "/reset-password"
    | "/sign-in"
    | "/sign-up"
    | "/feedback-widget/$organizationId"
    | "/s/$"
    | "/s/robots.txt"
    | "/s/sitemap.xml"
    | "/s/changelog/rss.xml"
    | "/$organizationId/settings/billing"
    | "/$organizationId/settings/changelog-categories"
    | "/$organizationId/settings/changelog-privacy"
    | "/$organizationId/settings/custom-attributes"
    | "/$organizationId/settings/customize"
    | "/$organizationId/settings/feedback-tags"
    | "/$organizationId/settings/members"
    | "/$organizationId/settings/preferences"
    | "/$organizationId/settings/profile"
    | "/$organizationId/settings/roadmap"
    | "/$organizationId/settings/security"
    | "/$organizationId/settings/workspace"
    | "/$organizationId/settings"
    | "/$organizationId/changelog/draft"
    | "/$organizationId/changelog/published"
    | "/$organizationId/feedback/active"
    | "/$organizationId/feedback/backlog"
    | "/$organizationId/roadmap/$slug"
    | "/$organizationId/settings/webhooks/$connectionId"
    | "/$organizationId/changelog"
    | "/$organizationId/company"
    | "/$organizationId/contact"
    | "/$organizationId/feedback"
    | "/$organizationId/roadmap"
    | "/$organizationId/settings/integrations"
    | "/$organizationId/settings/webhooks"
    | "/$organizationId/board/$boardSlug/active"
    | "/$organizationId/board/$boardSlug/backlog"
    | "/$organizationId/changelog/edit/$changelogSlug"
    | "/$organizationId/post/$boardSlug/$postSlug"
    | "/$organizationId/board/$boardSlug"
    | "/$organizationId/settings/integrations/discord"
    | "/$organizationId/settings/integrations/github"
    | "/$organizationId/settings/integrations/slack"
  id:
    | "__root__"
    | "/_dashboard"
    | "/robots.txt"
    | "/_dashboard/$"
    | "/_dashboard/$organizationId"
    | "/_dashboard/email-verify"
    | "/_dashboard/forgot-password"
    | "/_dashboard/register"
    | "/_dashboard/reset-password"
    | "/_dashboard/sign-in"
    | "/_dashboard/sign-up"
    | "/feedback-widget/$organizationId"
    | "/s/$"
    | "/s/robots.txt"
    | "/s/sitemap.xml"
    | "/_dashboard/$organizationId/_dashboard-layout"
    | "/_dashboard/$organizationId/settings"
    | "/s/changelog/rss.xml"
    | "/_dashboard/$organizationId/settings/billing"
    | "/_dashboard/$organizationId/settings/changelog-categories"
    | "/_dashboard/$organizationId/settings/changelog-privacy"
    | "/_dashboard/$organizationId/settings/custom-attributes"
    | "/_dashboard/$organizationId/settings/customize"
    | "/_dashboard/$organizationId/settings/feedback-tags"
    | "/_dashboard/$organizationId/settings/members"
    | "/_dashboard/$organizationId/settings/preferences"
    | "/_dashboard/$organizationId/settings/profile"
    | "/_dashboard/$organizationId/settings/roadmap"
    | "/_dashboard/$organizationId/settings/security"
    | "/_dashboard/$organizationId/settings/workspace"
    | "/_dashboard/$organizationId/_dashboard-layout/"
    | "/_dashboard/$organizationId/settings/"
    | "/_dashboard/$organizationId/_dashboard-layout/changelog/draft"
    | "/_dashboard/$organizationId/_dashboard-layout/changelog/published"
    | "/_dashboard/$organizationId/_dashboard-layout/feedback/active"
    | "/_dashboard/$organizationId/_dashboard-layout/feedback/backlog"
    | "/_dashboard/$organizationId/_dashboard-layout/roadmap/$slug"
    | "/_dashboard/$organizationId/settings/webhooks/$connectionId"
    | "/_dashboard/$organizationId/_dashboard-layout/changelog/"
    | "/_dashboard/$organizationId/_dashboard-layout/company/"
    | "/_dashboard/$organizationId/_dashboard-layout/contact/"
    | "/_dashboard/$organizationId/_dashboard-layout/feedback/"
    | "/_dashboard/$organizationId/_dashboard-layout/roadmap/"
    | "/_dashboard/$organizationId/settings/integrations/"
    | "/_dashboard/$organizationId/settings/webhooks/"
    | "/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/active"
    | "/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/backlog"
    | "/_dashboard/$organizationId/_dashboard-layout/changelog/edit/$changelogSlug"
    | "/_dashboard/$organizationId/_dashboard-layout/post/$boardSlug/$postSlug"
    | "/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/"
    | "/_dashboard/$organizationId/settings/integrations/discord/"
    | "/_dashboard/$organizationId/settings/integrations/github/"
    | "/_dashboard/$organizationId/settings/integrations/slack/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  FeedbackWidgetOrganizationIdRoute: typeof FeedbackWidgetOrganizationIdRoute
  SSplatRoute: typeof SSplatRoute
  SRobotsDottxtRoute: typeof SRobotsDottxtRoute
  SSitemapDotxmlRoute: typeof SSitemapDotxmlRoute
  SChangelogRssDotxmlRoute: typeof SChangelogRssDotxmlRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_dashboard": {
      id: "/_dashboard"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/robots.txt": {
      id: "/robots.txt"
      path: "/robots.txt"
      fullPath: "/robots.txt"
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_dashboard/$": {
      id: "/_dashboard/$"
      path: "/$"
      fullPath: "/$"
      preLoaderRoute: typeof DashboardSplatRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/$organizationId": {
      id: "/_dashboard/$organizationId"
      path: "/$organizationId"
      fullPath: "/$organizationId"
      preLoaderRoute: typeof DashboardOrganizationIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/email-verify": {
      id: "/_dashboard/email-verify"
      path: "/email-verify"
      fullPath: "/email-verify"
      preLoaderRoute: typeof DashboardEmailVerifyRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/forgot-password": {
      id: "/_dashboard/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof DashboardForgotPasswordRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/register": {
      id: "/_dashboard/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof DashboardRegisterRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/reset-password": {
      id: "/_dashboard/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof DashboardResetPasswordRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/sign-in": {
      id: "/_dashboard/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof DashboardSignInRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/sign-up": {
      id: "/_dashboard/sign-up"
      path: "/sign-up"
      fullPath: "/sign-up"
      preLoaderRoute: typeof DashboardSignUpRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/feedback-widget/$organizationId": {
      id: "/feedback-widget/$organizationId"
      path: "/feedback-widget/$organizationId"
      fullPath: "/feedback-widget/$organizationId"
      preLoaderRoute: typeof FeedbackWidgetOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/s/$": {
      id: "/s/$"
      path: "/s/$"
      fullPath: "/s/$"
      preLoaderRoute: typeof SSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/s/robots.txt": {
      id: "/s/robots.txt"
      path: "/s/robots.txt"
      fullPath: "/s/robots.txt"
      preLoaderRoute: typeof SRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/s/sitemap.xml": {
      id: "/s/sitemap.xml"
      path: "/s/sitemap.xml"
      fullPath: "/s/sitemap.xml"
      preLoaderRoute: typeof SSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_dashboard/$organizationId/_dashboard-layout": {
      id: "/_dashboard/$organizationId/_dashboard-layout"
      path: ""
      fullPath: "/$organizationId"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutRouteImport
      parentRoute: typeof DashboardOrganizationIdRoute
    }
    "/_dashboard/$organizationId/settings": {
      id: "/_dashboard/$organizationId/settings"
      path: "/settings"
      fullPath: "/$organizationId/settings"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsRouteImport
      parentRoute: typeof DashboardOrganizationIdRoute
    }
    "/s/changelog/rss.xml": {
      id: "/s/changelog/rss.xml"
      path: "/s/changelog/rss.xml"
      fullPath: "/s/changelog/rss.xml"
      preLoaderRoute: typeof SChangelogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_dashboard/$organizationId/_dashboard-layout/": {
      id: "/_dashboard/$organizationId/_dashboard-layout/"
      path: "/"
      fullPath: "/$organizationId/"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/settings/": {
      id: "/_dashboard/$organizationId/settings/"
      path: "/"
      fullPath: "/$organizationId/settings/"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/billing": {
      id: "/_dashboard/$organizationId/settings/billing"
      path: "/billing"
      fullPath: "/$organizationId/settings/billing"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsBillingRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/changelog-categories": {
      id: "/_dashboard/$organizationId/settings/changelog-categories"
      path: "/changelog-categories"
      fullPath: "/$organizationId/settings/changelog-categories"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsChangelogCategoriesRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/changelog-privacy": {
      id: "/_dashboard/$organizationId/settings/changelog-privacy"
      path: "/changelog-privacy"
      fullPath: "/$organizationId/settings/changelog-privacy"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsChangelogPrivacyRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/custom-attributes": {
      id: "/_dashboard/$organizationId/settings/custom-attributes"
      path: "/custom-attributes"
      fullPath: "/$organizationId/settings/custom-attributes"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsCustomAttributesRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/customize": {
      id: "/_dashboard/$organizationId/settings/customize"
      path: "/customize"
      fullPath: "/$organizationId/settings/customize"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsCustomizeRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/feedback-tags": {
      id: "/_dashboard/$organizationId/settings/feedback-tags"
      path: "/feedback-tags"
      fullPath: "/$organizationId/settings/feedback-tags"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsFeedbackTagsRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/members": {
      id: "/_dashboard/$organizationId/settings/members"
      path: "/members"
      fullPath: "/$organizationId/settings/members"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsMembersRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/preferences": {
      id: "/_dashboard/$organizationId/settings/preferences"
      path: "/preferences"
      fullPath: "/$organizationId/settings/preferences"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsPreferencesRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/profile": {
      id: "/_dashboard/$organizationId/settings/profile"
      path: "/profile"
      fullPath: "/$organizationId/settings/profile"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsProfileRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/roadmap": {
      id: "/_dashboard/$organizationId/settings/roadmap"
      path: "/roadmap"
      fullPath: "/$organizationId/settings/roadmap"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsRoadmapRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/security": {
      id: "/_dashboard/$organizationId/settings/security"
      path: "/security"
      fullPath: "/$organizationId/settings/security"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsSecurityRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/workspace": {
      id: "/_dashboard/$organizationId/settings/workspace"
      path: "/workspace"
      fullPath: "/$organizationId/settings/workspace"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsWorkspaceRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/changelog/": {
      id: "/_dashboard/$organizationId/_dashboard-layout/changelog/"
      path: "/changelog"
      fullPath: "/$organizationId/changelog/"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutChangelogIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/changelog/draft": {
      id: "/_dashboard/$organizationId/_dashboard-layout/changelog/draft"
      path: "/changelog/draft"
      fullPath: "/$organizationId/changelog/draft"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutChangelogDraftRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/changelog/published": {
      id: "/_dashboard/$organizationId/_dashboard-layout/changelog/published"
      path: "/changelog/published"
      fullPath: "/$organizationId/changelog/published"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutChangelogPublishedRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/company/": {
      id: "/_dashboard/$organizationId/_dashboard-layout/company/"
      path: "/company"
      fullPath: "/$organizationId/company/"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutCompanyIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/contact/": {
      id: "/_dashboard/$organizationId/_dashboard-layout/contact/"
      path: "/contact"
      fullPath: "/$organizationId/contact/"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutContactIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/feedback/": {
      id: "/_dashboard/$organizationId/_dashboard-layout/feedback/"
      path: "/feedback"
      fullPath: "/$organizationId/feedback/"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutFeedbackIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/feedback/active": {
      id: "/_dashboard/$organizationId/_dashboard-layout/feedback/active"
      path: "/feedback/active"
      fullPath: "/$organizationId/feedback/active"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutFeedbackActiveRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/feedback/backlog": {
      id: "/_dashboard/$organizationId/_dashboard-layout/feedback/backlog"
      path: "/feedback/backlog"
      fullPath: "/$organizationId/feedback/backlog"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutFeedbackBacklogRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/roadmap/": {
      id: "/_dashboard/$organizationId/_dashboard-layout/roadmap/"
      path: "/roadmap"
      fullPath: "/$organizationId/roadmap/"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutRoadmapIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/roadmap/$slug": {
      id: "/_dashboard/$organizationId/_dashboard-layout/roadmap/$slug"
      path: "/roadmap/$slug"
      fullPath: "/$organizationId/roadmap/$slug"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutRoadmapSlugRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/settings/integrations/": {
      id: "/_dashboard/$organizationId/settings/integrations/"
      path: "/integrations"
      fullPath: "/$organizationId/settings/integrations/"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsIntegrationsIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/webhooks/": {
      id: "/_dashboard/$organizationId/settings/webhooks/"
      path: "/webhooks"
      fullPath: "/$organizationId/settings/webhooks/"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsWebhooksIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/webhooks/$connectionId": {
      id: "/_dashboard/$organizationId/settings/webhooks/$connectionId"
      path: "/webhooks/$connectionId"
      fullPath: "/$organizationId/settings/webhooks/$connectionId"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsWebhooksConnectionIdRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/": {
      id: "/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/"
      path: "/board/$boardSlug"
      fullPath: "/$organizationId/board/$boardSlug/"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/active": {
      id: "/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/active"
      path: "/board/$boardSlug/active"
      fullPath: "/$organizationId/board/$boardSlug/active"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugActiveRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/backlog": {
      id: "/_dashboard/$organizationId/_dashboard-layout/board/$boardSlug/backlog"
      path: "/board/$boardSlug/backlog"
      fullPath: "/$organizationId/board/$boardSlug/backlog"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugBacklogRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/changelog/edit/$changelogSlug": {
      id: "/_dashboard/$organizationId/_dashboard-layout/changelog/edit/$changelogSlug"
      path: "/changelog/edit/$changelogSlug"
      fullPath: "/$organizationId/changelog/edit/$changelogSlug"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutChangelogEditChangelogSlugRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/_dashboard-layout/post/$boardSlug/$postSlug": {
      id: "/_dashboard/$organizationId/_dashboard-layout/post/$boardSlug/$postSlug"
      path: "/post/$boardSlug/$postSlug"
      fullPath: "/$organizationId/post/$boardSlug/$postSlug"
      preLoaderRoute: typeof DashboardOrganizationIdDashboardLayoutPostBoardSlugPostSlugRouteImport
      parentRoute: typeof DashboardOrganizationIdDashboardLayoutRoute
    }
    "/_dashboard/$organizationId/settings/integrations/discord/": {
      id: "/_dashboard/$organizationId/settings/integrations/discord/"
      path: "/integrations/discord"
      fullPath: "/$organizationId/settings/integrations/discord/"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsIntegrationsDiscordIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/integrations/github/": {
      id: "/_dashboard/$organizationId/settings/integrations/github/"
      path: "/integrations/github"
      fullPath: "/$organizationId/settings/integrations/github/"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsIntegrationsGithubIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
    "/_dashboard/$organizationId/settings/integrations/slack/": {
      id: "/_dashboard/$organizationId/settings/integrations/slack/"
      path: "/integrations/slack"
      fullPath: "/$organizationId/settings/integrations/slack/"
      preLoaderRoute: typeof DashboardOrganizationIdSettingsIntegrationsSlackIndexRouteImport
      parentRoute: typeof DashboardOrganizationIdSettingsRoute
    }
  }
}

interface DashboardOrganizationIdDashboardLayoutRouteChildren {
  DashboardOrganizationIdDashboardLayoutIndexRoute: typeof DashboardOrganizationIdDashboardLayoutIndexRoute
  DashboardOrganizationIdDashboardLayoutChangelogDraftRoute: typeof DashboardOrganizationIdDashboardLayoutChangelogDraftRoute
  DashboardOrganizationIdDashboardLayoutChangelogPublishedRoute: typeof DashboardOrganizationIdDashboardLayoutChangelogPublishedRoute
  DashboardOrganizationIdDashboardLayoutFeedbackActiveRoute: typeof DashboardOrganizationIdDashboardLayoutFeedbackActiveRoute
  DashboardOrganizationIdDashboardLayoutFeedbackBacklogRoute: typeof DashboardOrganizationIdDashboardLayoutFeedbackBacklogRoute
  DashboardOrganizationIdDashboardLayoutRoadmapSlugRoute: typeof DashboardOrganizationIdDashboardLayoutRoadmapSlugRoute
  DashboardOrganizationIdDashboardLayoutChangelogIndexRoute: typeof DashboardOrganizationIdDashboardLayoutChangelogIndexRoute
  DashboardOrganizationIdDashboardLayoutCompanyIndexRoute: typeof DashboardOrganizationIdDashboardLayoutCompanyIndexRoute
  DashboardOrganizationIdDashboardLayoutContactIndexRoute: typeof DashboardOrganizationIdDashboardLayoutContactIndexRoute
  DashboardOrganizationIdDashboardLayoutFeedbackIndexRoute: typeof DashboardOrganizationIdDashboardLayoutFeedbackIndexRoute
  DashboardOrganizationIdDashboardLayoutRoadmapIndexRoute: typeof DashboardOrganizationIdDashboardLayoutRoadmapIndexRoute
  DashboardOrganizationIdDashboardLayoutBoardBoardSlugActiveRoute: typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugActiveRoute
  DashboardOrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute: typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute
  DashboardOrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute: typeof DashboardOrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute
  DashboardOrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute: typeof DashboardOrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute
  DashboardOrganizationIdDashboardLayoutBoardBoardSlugIndexRoute: typeof DashboardOrganizationIdDashboardLayoutBoardBoardSlugIndexRoute
}

const DashboardOrganizationIdDashboardLayoutRouteChildren: DashboardOrganizationIdDashboardLayoutRouteChildren =
  {
    DashboardOrganizationIdDashboardLayoutIndexRoute:
      DashboardOrganizationIdDashboardLayoutIndexRoute,
    DashboardOrganizationIdDashboardLayoutChangelogDraftRoute:
      DashboardOrganizationIdDashboardLayoutChangelogDraftRoute,
    DashboardOrganizationIdDashboardLayoutChangelogPublishedRoute:
      DashboardOrganizationIdDashboardLayoutChangelogPublishedRoute,
    DashboardOrganizationIdDashboardLayoutFeedbackActiveRoute:
      DashboardOrganizationIdDashboardLayoutFeedbackActiveRoute,
    DashboardOrganizationIdDashboardLayoutFeedbackBacklogRoute:
      DashboardOrganizationIdDashboardLayoutFeedbackBacklogRoute,
    DashboardOrganizationIdDashboardLayoutRoadmapSlugRoute:
      DashboardOrganizationIdDashboardLayoutRoadmapSlugRoute,
    DashboardOrganizationIdDashboardLayoutChangelogIndexRoute:
      DashboardOrganizationIdDashboardLayoutChangelogIndexRoute,
    DashboardOrganizationIdDashboardLayoutCompanyIndexRoute:
      DashboardOrganizationIdDashboardLayoutCompanyIndexRoute,
    DashboardOrganizationIdDashboardLayoutContactIndexRoute:
      DashboardOrganizationIdDashboardLayoutContactIndexRoute,
    DashboardOrganizationIdDashboardLayoutFeedbackIndexRoute:
      DashboardOrganizationIdDashboardLayoutFeedbackIndexRoute,
    DashboardOrganizationIdDashboardLayoutRoadmapIndexRoute:
      DashboardOrganizationIdDashboardLayoutRoadmapIndexRoute,
    DashboardOrganizationIdDashboardLayoutBoardBoardSlugActiveRoute:
      DashboardOrganizationIdDashboardLayoutBoardBoardSlugActiveRoute,
    DashboardOrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute:
      DashboardOrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute,
    DashboardOrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute:
      DashboardOrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute,
    DashboardOrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute:
      DashboardOrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute,
    DashboardOrganizationIdDashboardLayoutBoardBoardSlugIndexRoute:
      DashboardOrganizationIdDashboardLayoutBoardBoardSlugIndexRoute,
  }

const DashboardOrganizationIdDashboardLayoutRouteWithChildren =
  DashboardOrganizationIdDashboardLayoutRoute._addFileChildren(
    DashboardOrganizationIdDashboardLayoutRouteChildren,
  )

interface DashboardOrganizationIdSettingsRouteChildren {
  DashboardOrganizationIdSettingsBillingRoute: typeof DashboardOrganizationIdSettingsBillingRoute
  DashboardOrganizationIdSettingsChangelogCategoriesRoute: typeof DashboardOrganizationIdSettingsChangelogCategoriesRoute
  DashboardOrganizationIdSettingsChangelogPrivacyRoute: typeof DashboardOrganizationIdSettingsChangelogPrivacyRoute
  DashboardOrganizationIdSettingsCustomAttributesRoute: typeof DashboardOrganizationIdSettingsCustomAttributesRoute
  DashboardOrganizationIdSettingsCustomizeRoute: typeof DashboardOrganizationIdSettingsCustomizeRoute
  DashboardOrganizationIdSettingsFeedbackTagsRoute: typeof DashboardOrganizationIdSettingsFeedbackTagsRoute
  DashboardOrganizationIdSettingsMembersRoute: typeof DashboardOrganizationIdSettingsMembersRoute
  DashboardOrganizationIdSettingsPreferencesRoute: typeof DashboardOrganizationIdSettingsPreferencesRoute
  DashboardOrganizationIdSettingsProfileRoute: typeof DashboardOrganizationIdSettingsProfileRoute
  DashboardOrganizationIdSettingsRoadmapRoute: typeof DashboardOrganizationIdSettingsRoadmapRoute
  DashboardOrganizationIdSettingsSecurityRoute: typeof DashboardOrganizationIdSettingsSecurityRoute
  DashboardOrganizationIdSettingsWorkspaceRoute: typeof DashboardOrganizationIdSettingsWorkspaceRoute
  DashboardOrganizationIdSettingsIndexRoute: typeof DashboardOrganizationIdSettingsIndexRoute
  DashboardOrganizationIdSettingsWebhooksConnectionIdRoute: typeof DashboardOrganizationIdSettingsWebhooksConnectionIdRoute
  DashboardOrganizationIdSettingsIntegrationsIndexRoute: typeof DashboardOrganizationIdSettingsIntegrationsIndexRoute
  DashboardOrganizationIdSettingsWebhooksIndexRoute: typeof DashboardOrganizationIdSettingsWebhooksIndexRoute
  DashboardOrganizationIdSettingsIntegrationsDiscordIndexRoute: typeof DashboardOrganizationIdSettingsIntegrationsDiscordIndexRoute
  DashboardOrganizationIdSettingsIntegrationsGithubIndexRoute: typeof DashboardOrganizationIdSettingsIntegrationsGithubIndexRoute
  DashboardOrganizationIdSettingsIntegrationsSlackIndexRoute: typeof DashboardOrganizationIdSettingsIntegrationsSlackIndexRoute
}

const DashboardOrganizationIdSettingsRouteChildren: DashboardOrganizationIdSettingsRouteChildren =
  {
    DashboardOrganizationIdSettingsBillingRoute:
      DashboardOrganizationIdSettingsBillingRoute,
    DashboardOrganizationIdSettingsChangelogCategoriesRoute:
      DashboardOrganizationIdSettingsChangelogCategoriesRoute,
    DashboardOrganizationIdSettingsChangelogPrivacyRoute:
      DashboardOrganizationIdSettingsChangelogPrivacyRoute,
    DashboardOrganizationIdSettingsCustomAttributesRoute:
      DashboardOrganizationIdSettingsCustomAttributesRoute,
    DashboardOrganizationIdSettingsCustomizeRoute:
      DashboardOrganizationIdSettingsCustomizeRoute,
    DashboardOrganizationIdSettingsFeedbackTagsRoute:
      DashboardOrganizationIdSettingsFeedbackTagsRoute,
    DashboardOrganizationIdSettingsMembersRoute:
      DashboardOrganizationIdSettingsMembersRoute,
    DashboardOrganizationIdSettingsPreferencesRoute:
      DashboardOrganizationIdSettingsPreferencesRoute,
    DashboardOrganizationIdSettingsProfileRoute:
      DashboardOrganizationIdSettingsProfileRoute,
    DashboardOrganizationIdSettingsRoadmapRoute:
      DashboardOrganizationIdSettingsRoadmapRoute,
    DashboardOrganizationIdSettingsSecurityRoute:
      DashboardOrganizationIdSettingsSecurityRoute,
    DashboardOrganizationIdSettingsWorkspaceRoute:
      DashboardOrganizationIdSettingsWorkspaceRoute,
    DashboardOrganizationIdSettingsIndexRoute:
      DashboardOrganizationIdSettingsIndexRoute,
    DashboardOrganizationIdSettingsWebhooksConnectionIdRoute:
      DashboardOrganizationIdSettingsWebhooksConnectionIdRoute,
    DashboardOrganizationIdSettingsIntegrationsIndexRoute:
      DashboardOrganizationIdSettingsIntegrationsIndexRoute,
    DashboardOrganizationIdSettingsWebhooksIndexRoute:
      DashboardOrganizationIdSettingsWebhooksIndexRoute,
    DashboardOrganizationIdSettingsIntegrationsDiscordIndexRoute:
      DashboardOrganizationIdSettingsIntegrationsDiscordIndexRoute,
    DashboardOrganizationIdSettingsIntegrationsGithubIndexRoute:
      DashboardOrganizationIdSettingsIntegrationsGithubIndexRoute,
    DashboardOrganizationIdSettingsIntegrationsSlackIndexRoute:
      DashboardOrganizationIdSettingsIntegrationsSlackIndexRoute,
  }

const DashboardOrganizationIdSettingsRouteWithChildren =
  DashboardOrganizationIdSettingsRoute._addFileChildren(
    DashboardOrganizationIdSettingsRouteChildren,
  )

interface DashboardOrganizationIdRouteChildren {
  DashboardOrganizationIdDashboardLayoutRoute: typeof DashboardOrganizationIdDashboardLayoutRouteWithChildren
  DashboardOrganizationIdSettingsRoute: typeof DashboardOrganizationIdSettingsRouteWithChildren
}

const DashboardOrganizationIdRouteChildren: DashboardOrganizationIdRouteChildren =
  {
    DashboardOrganizationIdDashboardLayoutRoute:
      DashboardOrganizationIdDashboardLayoutRouteWithChildren,
    DashboardOrganizationIdSettingsRoute:
      DashboardOrganizationIdSettingsRouteWithChildren,
  }

const DashboardOrganizationIdRouteWithChildren =
  DashboardOrganizationIdRoute._addFileChildren(
    DashboardOrganizationIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardSplatRoute: typeof DashboardSplatRoute
  DashboardOrganizationIdRoute: typeof DashboardOrganizationIdRouteWithChildren
  DashboardEmailVerifyRoute: typeof DashboardEmailVerifyRoute
  DashboardForgotPasswordRoute: typeof DashboardForgotPasswordRoute
  DashboardRegisterRoute: typeof DashboardRegisterRoute
  DashboardResetPasswordRoute: typeof DashboardResetPasswordRoute
  DashboardSignInRoute: typeof DashboardSignInRoute
  DashboardSignUpRoute: typeof DashboardSignUpRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSplatRoute: DashboardSplatRoute,
  DashboardOrganizationIdRoute: DashboardOrganizationIdRouteWithChildren,
  DashboardEmailVerifyRoute: DashboardEmailVerifyRoute,
  DashboardForgotPasswordRoute: DashboardForgotPasswordRoute,
  DashboardRegisterRoute: DashboardRegisterRoute,
  DashboardResetPasswordRoute: DashboardResetPasswordRoute,
  DashboardSignInRoute: DashboardSignInRoute,
  DashboardSignUpRoute: DashboardSignUpRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  FeedbackWidgetOrganizationIdRoute: FeedbackWidgetOrganizationIdRoute,
  SSplatRoute: SSplatRoute,
  SRobotsDottxtRoute: SRobotsDottxtRoute,
  SSitemapDotxmlRoute: SSitemapDotxmlRoute,
  SChangelogRssDotxmlRoute: SChangelogRssDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
