name: feeblo
services:
  pg:
    image: postgres:17-alpine
    container_name: feeblo-database
    environment:
      - POSTGRES_USER=feeblo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=feeblo
    ports:
      - 54323:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  smtp:
    image: axllent/mailpit
    container_name: feeblo-smtp
    ports:
      - 8025:8025
      - 1025:1025

  minio:
    image: minio/minio
    container_name: feeblo-minio
    ports:
      - 9002:9002
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=feeblo
      - MINIO_ROOT_PASSWORD=password

    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001" --address ":9002"'

  mc:
    image: minio/mc
    container_name: feeblo-mc
    depends_on:
      - minio
    entrypoint: sh
    command: |
      -c "
        sleep 10;
        mc alias set myminio http://minio:9002 feeblo password;
        mc mb myminio/feeblo-media-public;
        mc anonymous set download myminio/feeblo-media-public;
        exit 0;
      "

volumes:
  postgres:
  minio:
