/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SignUpRouteImport } from "./routes/sign-up"
import { Route as SignInRouteImport } from "./routes/sign-in"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as EmailVerifyRouteImport } from "./routes/email-verify"
import { Route as OrganizationIdRouteImport } from "./routes/$organizationId"
import { Route as OrganizationIdSettingsRouteImport } from "./routes/$organizationId/settings"
import { Route as OrganizationIdDashboardLayoutRouteImport } from "./routes/$organizationId/_dashboard-layout"
import { Route as OrganizationIdSettingsIndexRouteImport } from "./routes/$organizationId/settings/index"
import { Route as OrganizationIdDashboardLayoutIndexRouteImport } from "./routes/$organizationId/_dashboard-layout/index"
import { Route as OrganizationIdSettingsWorkspaceRouteImport } from "./routes/$organizationId/settings/workspace"
import { Route as OrganizationIdSettingsRoadmapRouteImport } from "./routes/$organizationId/settings/roadmap"
import { Route as OrganizationIdSettingsProfileRouteImport } from "./routes/$organizationId/settings/profile"
import { Route as OrganizationIdSettingsPreferencesRouteImport } from "./routes/$organizationId/settings/preferences"
import { Route as OrganizationIdSettingsMembersRouteImport } from "./routes/$organizationId/settings/members"
import { Route as OrganizationIdSettingsFeedbackTagsRouteImport } from "./routes/$organizationId/settings/feedback-tags"
import { Route as OrganizationIdSettingsCustomizeRouteImport } from "./routes/$organizationId/settings/customize"
import { Route as OrganizationIdSettingsChangelogTagsRouteImport } from "./routes/$organizationId/settings/changelog-tags"
import { Route as OrganizationIdSettingsChangelogPrivacyRouteImport } from "./routes/$organizationId/settings/changelog-privacy"
import { Route as OrganizationIdSettingsBillingRouteImport } from "./routes/$organizationId/settings/billing"
import { Route as OrganizationIdDashboardLayoutSettingsRouteImport } from "./routes/$organizationId/_dashboard-layout/settings"
import { Route as OrganizationIdDashboardLayoutRoadmapRouteImport } from "./routes/$organizationId/_dashboard-layout/roadmap"
import { Route as OrganizationIdDashboardLayoutFeedbackIndexRouteImport } from "./routes/$organizationId/_dashboard-layout/feedback/index"
import { Route as OrganizationIdDashboardLayoutChangelogIndexRouteImport } from "./routes/$organizationId/_dashboard-layout/changelog/index"
import { Route as OrganizationIdDashboardLayoutFeedbackBacklogRouteImport } from "./routes/$organizationId/_dashboard-layout/feedback/backlog"
import { Route as OrganizationIdDashboardLayoutFeedbackActiveRouteImport } from "./routes/$organizationId/_dashboard-layout/feedback/active"
import { Route as OrganizationIdDashboardLayoutChangelogPublishedRouteImport } from "./routes/$organizationId/_dashboard-layout/changelog/published"
import { Route as OrganizationIdDashboardLayoutChangelogDraftRouteImport } from "./routes/$organizationId/_dashboard-layout/changelog/draft"
import { Route as OrganizationIdDashboardLayoutBoardBoardSlugIndexRouteImport } from "./routes/$organizationId/_dashboard-layout/board/$boardSlug/index"
import { Route as OrganizationIdDashboardLayoutPostBoardSlugPostSlugRouteImport } from "./routes/$organizationId/_dashboard-layout/post/$boardSlug/$postSlug"
import { Route as OrganizationIdDashboardLayoutChangelogEditChangelogSlugRouteImport } from "./routes/$organizationId/_dashboard-layout/changelog/edit/$changelogSlug"
import { Route as OrganizationIdDashboardLayoutBoardBoardSlugBacklogRouteImport } from "./routes/$organizationId/_dashboard-layout/board/$boardSlug/backlog"
import { Route as OrganizationIdDashboardLayoutBoardBoardSlugActiveRouteImport } from "./routes/$organizationId/_dashboard-layout/board/$boardSlug/active"

const SignUpRoute = SignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifyRoute = EmailVerifyRouteImport.update({
  id: "/email-verify",
  path: "/email-verify",
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIdRoute = OrganizationIdRouteImport.update({
  id: "/$organizationId",
  path: "/$organizationId",
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIdSettingsRoute = OrganizationIdSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => OrganizationIdRoute,
} as any)
const OrganizationIdDashboardLayoutRoute =
  OrganizationIdDashboardLayoutRouteImport.update({
    id: "/_dashboard-layout",
    getParentRoute: () => OrganizationIdRoute,
  } as any)
const OrganizationIdSettingsIndexRoute =
  OrganizationIdSettingsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => OrganizationIdSettingsRoute,
  } as any)
const OrganizationIdDashboardLayoutIndexRoute =
  OrganizationIdDashboardLayoutIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdSettingsWorkspaceRoute =
  OrganizationIdSettingsWorkspaceRouteImport.update({
    id: "/workspace",
    path: "/workspace",
    getParentRoute: () => OrganizationIdSettingsRoute,
  } as any)
const OrganizationIdSettingsRoadmapRoute =
  OrganizationIdSettingsRoadmapRouteImport.update({
    id: "/roadmap",
    path: "/roadmap",
    getParentRoute: () => OrganizationIdSettingsRoute,
  } as any)
const OrganizationIdSettingsProfileRoute =
  OrganizationIdSettingsProfileRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => OrganizationIdSettingsRoute,
  } as any)
const OrganizationIdSettingsPreferencesRoute =
  OrganizationIdSettingsPreferencesRouteImport.update({
    id: "/preferences",
    path: "/preferences",
    getParentRoute: () => OrganizationIdSettingsRoute,
  } as any)
const OrganizationIdSettingsMembersRoute =
  OrganizationIdSettingsMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => OrganizationIdSettingsRoute,
  } as any)
const OrganizationIdSettingsFeedbackTagsRoute =
  OrganizationIdSettingsFeedbackTagsRouteImport.update({
    id: "/feedback-tags",
    path: "/feedback-tags",
    getParentRoute: () => OrganizationIdSettingsRoute,
  } as any)
const OrganizationIdSettingsCustomizeRoute =
  OrganizationIdSettingsCustomizeRouteImport.update({
    id: "/customize",
    path: "/customize",
    getParentRoute: () => OrganizationIdSettingsRoute,
  } as any)
const OrganizationIdSettingsChangelogTagsRoute =
  OrganizationIdSettingsChangelogTagsRouteImport.update({
    id: "/changelog-tags",
    path: "/changelog-tags",
    getParentRoute: () => OrganizationIdSettingsRoute,
  } as any)
const OrganizationIdSettingsChangelogPrivacyRoute =
  OrganizationIdSettingsChangelogPrivacyRouteImport.update({
    id: "/changelog-privacy",
    path: "/changelog-privacy",
    getParentRoute: () => OrganizationIdSettingsRoute,
  } as any)
const OrganizationIdSettingsBillingRoute =
  OrganizationIdSettingsBillingRouteImport.update({
    id: "/billing",
    path: "/billing",
    getParentRoute: () => OrganizationIdSettingsRoute,
  } as any)
const OrganizationIdDashboardLayoutSettingsRoute =
  OrganizationIdDashboardLayoutSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdDashboardLayoutRoadmapRoute =
  OrganizationIdDashboardLayoutRoadmapRouteImport.update({
    id: "/roadmap",
    path: "/roadmap",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdDashboardLayoutFeedbackIndexRoute =
  OrganizationIdDashboardLayoutFeedbackIndexRouteImport.update({
    id: "/feedback/",
    path: "/feedback/",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdDashboardLayoutChangelogIndexRoute =
  OrganizationIdDashboardLayoutChangelogIndexRouteImport.update({
    id: "/changelog/",
    path: "/changelog/",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdDashboardLayoutFeedbackBacklogRoute =
  OrganizationIdDashboardLayoutFeedbackBacklogRouteImport.update({
    id: "/feedback/backlog",
    path: "/feedback/backlog",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdDashboardLayoutFeedbackActiveRoute =
  OrganizationIdDashboardLayoutFeedbackActiveRouteImport.update({
    id: "/feedback/active",
    path: "/feedback/active",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdDashboardLayoutChangelogPublishedRoute =
  OrganizationIdDashboardLayoutChangelogPublishedRouteImport.update({
    id: "/changelog/published",
    path: "/changelog/published",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdDashboardLayoutChangelogDraftRoute =
  OrganizationIdDashboardLayoutChangelogDraftRouteImport.update({
    id: "/changelog/draft",
    path: "/changelog/draft",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdDashboardLayoutBoardBoardSlugIndexRoute =
  OrganizationIdDashboardLayoutBoardBoardSlugIndexRouteImport.update({
    id: "/board/$boardSlug/",
    path: "/board/$boardSlug/",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute =
  OrganizationIdDashboardLayoutPostBoardSlugPostSlugRouteImport.update({
    id: "/post/$boardSlug/$postSlug",
    path: "/post/$boardSlug/$postSlug",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute =
  OrganizationIdDashboardLayoutChangelogEditChangelogSlugRouteImport.update({
    id: "/changelog/edit/$changelogSlug",
    path: "/changelog/edit/$changelogSlug",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute =
  OrganizationIdDashboardLayoutBoardBoardSlugBacklogRouteImport.update({
    id: "/board/$boardSlug/backlog",
    path: "/board/$boardSlug/backlog",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)
const OrganizationIdDashboardLayoutBoardBoardSlugActiveRoute =
  OrganizationIdDashboardLayoutBoardBoardSlugActiveRouteImport.update({
    id: "/board/$boardSlug/active",
    path: "/board/$boardSlug/active",
    getParentRoute: () => OrganizationIdDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/$organizationId": typeof OrganizationIdDashboardLayoutRouteWithChildren
  "/email-verify": typeof EmailVerifyRoute
  "/register": typeof RegisterRoute
  "/sign-in": typeof SignInRoute
  "/sign-up": typeof SignUpRoute
  "/$organizationId/settings": typeof OrganizationIdDashboardLayoutSettingsRoute
  "/$organizationId/roadmap": typeof OrganizationIdDashboardLayoutRoadmapRoute
  "/$organizationId/settings/billing": typeof OrganizationIdSettingsBillingRoute
  "/$organizationId/settings/changelog-privacy": typeof OrganizationIdSettingsChangelogPrivacyRoute
  "/$organizationId/settings/changelog-tags": typeof OrganizationIdSettingsChangelogTagsRoute
  "/$organizationId/settings/customize": typeof OrganizationIdSettingsCustomizeRoute
  "/$organizationId/settings/feedback-tags": typeof OrganizationIdSettingsFeedbackTagsRoute
  "/$organizationId/settings/members": typeof OrganizationIdSettingsMembersRoute
  "/$organizationId/settings/preferences": typeof OrganizationIdSettingsPreferencesRoute
  "/$organizationId/settings/profile": typeof OrganizationIdSettingsProfileRoute
  "/$organizationId/settings/roadmap": typeof OrganizationIdSettingsRoadmapRoute
  "/$organizationId/settings/workspace": typeof OrganizationIdSettingsWorkspaceRoute
  "/$organizationId/": typeof OrganizationIdDashboardLayoutIndexRoute
  "/$organizationId/settings/": typeof OrganizationIdSettingsIndexRoute
  "/$organizationId/changelog/draft": typeof OrganizationIdDashboardLayoutChangelogDraftRoute
  "/$organizationId/changelog/published": typeof OrganizationIdDashboardLayoutChangelogPublishedRoute
  "/$organizationId/feedback/active": typeof OrganizationIdDashboardLayoutFeedbackActiveRoute
  "/$organizationId/feedback/backlog": typeof OrganizationIdDashboardLayoutFeedbackBacklogRoute
  "/$organizationId/changelog/": typeof OrganizationIdDashboardLayoutChangelogIndexRoute
  "/$organizationId/feedback/": typeof OrganizationIdDashboardLayoutFeedbackIndexRoute
  "/$organizationId/board/$boardSlug/active": typeof OrganizationIdDashboardLayoutBoardBoardSlugActiveRoute
  "/$organizationId/board/$boardSlug/backlog": typeof OrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute
  "/$organizationId/changelog/edit/$changelogSlug": typeof OrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute
  "/$organizationId/post/$boardSlug/$postSlug": typeof OrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute
  "/$organizationId/board/$boardSlug/": typeof OrganizationIdDashboardLayoutBoardBoardSlugIndexRoute
}
export interface FileRoutesByTo {
  "/$organizationId": typeof OrganizationIdDashboardLayoutIndexRoute
  "/email-verify": typeof EmailVerifyRoute
  "/register": typeof RegisterRoute
  "/sign-in": typeof SignInRoute
  "/sign-up": typeof SignUpRoute
  "/$organizationId/roadmap": typeof OrganizationIdDashboardLayoutRoadmapRoute
  "/$organizationId/settings": typeof OrganizationIdSettingsIndexRoute
  "/$organizationId/settings/billing": typeof OrganizationIdSettingsBillingRoute
  "/$organizationId/settings/changelog-privacy": typeof OrganizationIdSettingsChangelogPrivacyRoute
  "/$organizationId/settings/changelog-tags": typeof OrganizationIdSettingsChangelogTagsRoute
  "/$organizationId/settings/customize": typeof OrganizationIdSettingsCustomizeRoute
  "/$organizationId/settings/feedback-tags": typeof OrganizationIdSettingsFeedbackTagsRoute
  "/$organizationId/settings/members": typeof OrganizationIdSettingsMembersRoute
  "/$organizationId/settings/preferences": typeof OrganizationIdSettingsPreferencesRoute
  "/$organizationId/settings/profile": typeof OrganizationIdSettingsProfileRoute
  "/$organizationId/settings/roadmap": typeof OrganizationIdSettingsRoadmapRoute
  "/$organizationId/settings/workspace": typeof OrganizationIdSettingsWorkspaceRoute
  "/$organizationId/changelog/draft": typeof OrganizationIdDashboardLayoutChangelogDraftRoute
  "/$organizationId/changelog/published": typeof OrganizationIdDashboardLayoutChangelogPublishedRoute
  "/$organizationId/feedback/active": typeof OrganizationIdDashboardLayoutFeedbackActiveRoute
  "/$organizationId/feedback/backlog": typeof OrganizationIdDashboardLayoutFeedbackBacklogRoute
  "/$organizationId/changelog": typeof OrganizationIdDashboardLayoutChangelogIndexRoute
  "/$organizationId/feedback": typeof OrganizationIdDashboardLayoutFeedbackIndexRoute
  "/$organizationId/board/$boardSlug/active": typeof OrganizationIdDashboardLayoutBoardBoardSlugActiveRoute
  "/$organizationId/board/$boardSlug/backlog": typeof OrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute
  "/$organizationId/changelog/edit/$changelogSlug": typeof OrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute
  "/$organizationId/post/$boardSlug/$postSlug": typeof OrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute
  "/$organizationId/board/$boardSlug": typeof OrganizationIdDashboardLayoutBoardBoardSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/$organizationId": typeof OrganizationIdRouteWithChildren
  "/email-verify": typeof EmailVerifyRoute
  "/register": typeof RegisterRoute
  "/sign-in": typeof SignInRoute
  "/sign-up": typeof SignUpRoute
  "/$organizationId/_dashboard-layout": typeof OrganizationIdDashboardLayoutRouteWithChildren
  "/$organizationId/settings": typeof OrganizationIdSettingsRouteWithChildren
  "/$organizationId/_dashboard-layout/roadmap": typeof OrganizationIdDashboardLayoutRoadmapRoute
  "/$organizationId/_dashboard-layout/settings": typeof OrganizationIdDashboardLayoutSettingsRoute
  "/$organizationId/settings/billing": typeof OrganizationIdSettingsBillingRoute
  "/$organizationId/settings/changelog-privacy": typeof OrganizationIdSettingsChangelogPrivacyRoute
  "/$organizationId/settings/changelog-tags": typeof OrganizationIdSettingsChangelogTagsRoute
  "/$organizationId/settings/customize": typeof OrganizationIdSettingsCustomizeRoute
  "/$organizationId/settings/feedback-tags": typeof OrganizationIdSettingsFeedbackTagsRoute
  "/$organizationId/settings/members": typeof OrganizationIdSettingsMembersRoute
  "/$organizationId/settings/preferences": typeof OrganizationIdSettingsPreferencesRoute
  "/$organizationId/settings/profile": typeof OrganizationIdSettingsProfileRoute
  "/$organizationId/settings/roadmap": typeof OrganizationIdSettingsRoadmapRoute
  "/$organizationId/settings/workspace": typeof OrganizationIdSettingsWorkspaceRoute
  "/$organizationId/_dashboard-layout/": typeof OrganizationIdDashboardLayoutIndexRoute
  "/$organizationId/settings/": typeof OrganizationIdSettingsIndexRoute
  "/$organizationId/_dashboard-layout/changelog/draft": typeof OrganizationIdDashboardLayoutChangelogDraftRoute
  "/$organizationId/_dashboard-layout/changelog/published": typeof OrganizationIdDashboardLayoutChangelogPublishedRoute
  "/$organizationId/_dashboard-layout/feedback/active": typeof OrganizationIdDashboardLayoutFeedbackActiveRoute
  "/$organizationId/_dashboard-layout/feedback/backlog": typeof OrganizationIdDashboardLayoutFeedbackBacklogRoute
  "/$organizationId/_dashboard-layout/changelog/": typeof OrganizationIdDashboardLayoutChangelogIndexRoute
  "/$organizationId/_dashboard-layout/feedback/": typeof OrganizationIdDashboardLayoutFeedbackIndexRoute
  "/$organizationId/_dashboard-layout/board/$boardSlug/active": typeof OrganizationIdDashboardLayoutBoardBoardSlugActiveRoute
  "/$organizationId/_dashboard-layout/board/$boardSlug/backlog": typeof OrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute
  "/$organizationId/_dashboard-layout/changelog/edit/$changelogSlug": typeof OrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute
  "/$organizationId/_dashboard-layout/post/$boardSlug/$postSlug": typeof OrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute
  "/$organizationId/_dashboard-layout/board/$boardSlug/": typeof OrganizationIdDashboardLayoutBoardBoardSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/$organizationId"
    | "/email-verify"
    | "/register"
    | "/sign-in"
    | "/sign-up"
    | "/$organizationId/settings"
    | "/$organizationId/roadmap"
    | "/$organizationId/settings/billing"
    | "/$organizationId/settings/changelog-privacy"
    | "/$organizationId/settings/changelog-tags"
    | "/$organizationId/settings/customize"
    | "/$organizationId/settings/feedback-tags"
    | "/$organizationId/settings/members"
    | "/$organizationId/settings/preferences"
    | "/$organizationId/settings/profile"
    | "/$organizationId/settings/roadmap"
    | "/$organizationId/settings/workspace"
    | "/$organizationId/"
    | "/$organizationId/settings/"
    | "/$organizationId/changelog/draft"
    | "/$organizationId/changelog/published"
    | "/$organizationId/feedback/active"
    | "/$organizationId/feedback/backlog"
    | "/$organizationId/changelog/"
    | "/$organizationId/feedback/"
    | "/$organizationId/board/$boardSlug/active"
    | "/$organizationId/board/$boardSlug/backlog"
    | "/$organizationId/changelog/edit/$changelogSlug"
    | "/$organizationId/post/$boardSlug/$postSlug"
    | "/$organizationId/board/$boardSlug/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/$organizationId"
    | "/email-verify"
    | "/register"
    | "/sign-in"
    | "/sign-up"
    | "/$organizationId/roadmap"
    | "/$organizationId/settings"
    | "/$organizationId/settings/billing"
    | "/$organizationId/settings/changelog-privacy"
    | "/$organizationId/settings/changelog-tags"
    | "/$organizationId/settings/customize"
    | "/$organizationId/settings/feedback-tags"
    | "/$organizationId/settings/members"
    | "/$organizationId/settings/preferences"
    | "/$organizationId/settings/profile"
    | "/$organizationId/settings/roadmap"
    | "/$organizationId/settings/workspace"
    | "/$organizationId/changelog/draft"
    | "/$organizationId/changelog/published"
    | "/$organizationId/feedback/active"
    | "/$organizationId/feedback/backlog"
    | "/$organizationId/changelog"
    | "/$organizationId/feedback"
    | "/$organizationId/board/$boardSlug/active"
    | "/$organizationId/board/$boardSlug/backlog"
    | "/$organizationId/changelog/edit/$changelogSlug"
    | "/$organizationId/post/$boardSlug/$postSlug"
    | "/$organizationId/board/$boardSlug"
  id:
    | "__root__"
    | "/$organizationId"
    | "/email-verify"
    | "/register"
    | "/sign-in"
    | "/sign-up"
    | "/$organizationId/_dashboard-layout"
    | "/$organizationId/settings"
    | "/$organizationId/_dashboard-layout/roadmap"
    | "/$organizationId/_dashboard-layout/settings"
    | "/$organizationId/settings/billing"
    | "/$organizationId/settings/changelog-privacy"
    | "/$organizationId/settings/changelog-tags"
    | "/$organizationId/settings/customize"
    | "/$organizationId/settings/feedback-tags"
    | "/$organizationId/settings/members"
    | "/$organizationId/settings/preferences"
    | "/$organizationId/settings/profile"
    | "/$organizationId/settings/roadmap"
    | "/$organizationId/settings/workspace"
    | "/$organizationId/_dashboard-layout/"
    | "/$organizationId/settings/"
    | "/$organizationId/_dashboard-layout/changelog/draft"
    | "/$organizationId/_dashboard-layout/changelog/published"
    | "/$organizationId/_dashboard-layout/feedback/active"
    | "/$organizationId/_dashboard-layout/feedback/backlog"
    | "/$organizationId/_dashboard-layout/changelog/"
    | "/$organizationId/_dashboard-layout/feedback/"
    | "/$organizationId/_dashboard-layout/board/$boardSlug/active"
    | "/$organizationId/_dashboard-layout/board/$boardSlug/backlog"
    | "/$organizationId/_dashboard-layout/changelog/edit/$changelogSlug"
    | "/$organizationId/_dashboard-layout/post/$boardSlug/$postSlug"
    | "/$organizationId/_dashboard-layout/board/$boardSlug/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OrganizationIdRoute: typeof OrganizationIdRouteWithChildren
  EmailVerifyRoute: typeof EmailVerifyRoute
  RegisterRoute: typeof RegisterRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-up": {
      id: "/sign-up"
      path: "/sign-up"
      fullPath: "/sign-up"
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sign-in": {
      id: "/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/email-verify": {
      id: "/email-verify"
      path: "/email-verify"
      fullPath: "/email-verify"
      preLoaderRoute: typeof EmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$organizationId": {
      id: "/$organizationId"
      path: "/$organizationId"
      fullPath: "/$organizationId"
      preLoaderRoute: typeof OrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$organizationId/settings": {
      id: "/$organizationId/settings"
      path: "/settings"
      fullPath: "/$organizationId/settings"
      preLoaderRoute: typeof OrganizationIdSettingsRouteImport
      parentRoute: typeof OrganizationIdRoute
    }
    "/$organizationId/_dashboard-layout": {
      id: "/$organizationId/_dashboard-layout"
      path: ""
      fullPath: "/$organizationId"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutRouteImport
      parentRoute: typeof OrganizationIdRoute
    }
    "/$organizationId/settings/": {
      id: "/$organizationId/settings/"
      path: "/"
      fullPath: "/$organizationId/settings/"
      preLoaderRoute: typeof OrganizationIdSettingsIndexRouteImport
      parentRoute: typeof OrganizationIdSettingsRoute
    }
    "/$organizationId/_dashboard-layout/": {
      id: "/$organizationId/_dashboard-layout/"
      path: "/"
      fullPath: "/$organizationId/"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutIndexRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/settings/workspace": {
      id: "/$organizationId/settings/workspace"
      path: "/workspace"
      fullPath: "/$organizationId/settings/workspace"
      preLoaderRoute: typeof OrganizationIdSettingsWorkspaceRouteImport
      parentRoute: typeof OrganizationIdSettingsRoute
    }
    "/$organizationId/settings/roadmap": {
      id: "/$organizationId/settings/roadmap"
      path: "/roadmap"
      fullPath: "/$organizationId/settings/roadmap"
      preLoaderRoute: typeof OrganizationIdSettingsRoadmapRouteImport
      parentRoute: typeof OrganizationIdSettingsRoute
    }
    "/$organizationId/settings/profile": {
      id: "/$organizationId/settings/profile"
      path: "/profile"
      fullPath: "/$organizationId/settings/profile"
      preLoaderRoute: typeof OrganizationIdSettingsProfileRouteImport
      parentRoute: typeof OrganizationIdSettingsRoute
    }
    "/$organizationId/settings/preferences": {
      id: "/$organizationId/settings/preferences"
      path: "/preferences"
      fullPath: "/$organizationId/settings/preferences"
      preLoaderRoute: typeof OrganizationIdSettingsPreferencesRouteImport
      parentRoute: typeof OrganizationIdSettingsRoute
    }
    "/$organizationId/settings/members": {
      id: "/$organizationId/settings/members"
      path: "/members"
      fullPath: "/$organizationId/settings/members"
      preLoaderRoute: typeof OrganizationIdSettingsMembersRouteImport
      parentRoute: typeof OrganizationIdSettingsRoute
    }
    "/$organizationId/settings/feedback-tags": {
      id: "/$organizationId/settings/feedback-tags"
      path: "/feedback-tags"
      fullPath: "/$organizationId/settings/feedback-tags"
      preLoaderRoute: typeof OrganizationIdSettingsFeedbackTagsRouteImport
      parentRoute: typeof OrganizationIdSettingsRoute
    }
    "/$organizationId/settings/customize": {
      id: "/$organizationId/settings/customize"
      path: "/customize"
      fullPath: "/$organizationId/settings/customize"
      preLoaderRoute: typeof OrganizationIdSettingsCustomizeRouteImport
      parentRoute: typeof OrganizationIdSettingsRoute
    }
    "/$organizationId/settings/changelog-tags": {
      id: "/$organizationId/settings/changelog-tags"
      path: "/changelog-tags"
      fullPath: "/$organizationId/settings/changelog-tags"
      preLoaderRoute: typeof OrganizationIdSettingsChangelogTagsRouteImport
      parentRoute: typeof OrganizationIdSettingsRoute
    }
    "/$organizationId/settings/changelog-privacy": {
      id: "/$organizationId/settings/changelog-privacy"
      path: "/changelog-privacy"
      fullPath: "/$organizationId/settings/changelog-privacy"
      preLoaderRoute: typeof OrganizationIdSettingsChangelogPrivacyRouteImport
      parentRoute: typeof OrganizationIdSettingsRoute
    }
    "/$organizationId/settings/billing": {
      id: "/$organizationId/settings/billing"
      path: "/billing"
      fullPath: "/$organizationId/settings/billing"
      preLoaderRoute: typeof OrganizationIdSettingsBillingRouteImport
      parentRoute: typeof OrganizationIdSettingsRoute
    }
    "/$organizationId/_dashboard-layout/settings": {
      id: "/$organizationId/_dashboard-layout/settings"
      path: "/settings"
      fullPath: "/$organizationId/settings"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutSettingsRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/_dashboard-layout/roadmap": {
      id: "/$organizationId/_dashboard-layout/roadmap"
      path: "/roadmap"
      fullPath: "/$organizationId/roadmap"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutRoadmapRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/_dashboard-layout/feedback/": {
      id: "/$organizationId/_dashboard-layout/feedback/"
      path: "/feedback"
      fullPath: "/$organizationId/feedback/"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutFeedbackIndexRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/_dashboard-layout/changelog/": {
      id: "/$organizationId/_dashboard-layout/changelog/"
      path: "/changelog"
      fullPath: "/$organizationId/changelog/"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutChangelogIndexRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/_dashboard-layout/feedback/backlog": {
      id: "/$organizationId/_dashboard-layout/feedback/backlog"
      path: "/feedback/backlog"
      fullPath: "/$organizationId/feedback/backlog"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutFeedbackBacklogRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/_dashboard-layout/feedback/active": {
      id: "/$organizationId/_dashboard-layout/feedback/active"
      path: "/feedback/active"
      fullPath: "/$organizationId/feedback/active"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutFeedbackActiveRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/_dashboard-layout/changelog/published": {
      id: "/$organizationId/_dashboard-layout/changelog/published"
      path: "/changelog/published"
      fullPath: "/$organizationId/changelog/published"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutChangelogPublishedRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/_dashboard-layout/changelog/draft": {
      id: "/$organizationId/_dashboard-layout/changelog/draft"
      path: "/changelog/draft"
      fullPath: "/$organizationId/changelog/draft"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutChangelogDraftRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/_dashboard-layout/board/$boardSlug/": {
      id: "/$organizationId/_dashboard-layout/board/$boardSlug/"
      path: "/board/$boardSlug"
      fullPath: "/$organizationId/board/$boardSlug/"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutBoardBoardSlugIndexRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/_dashboard-layout/post/$boardSlug/$postSlug": {
      id: "/$organizationId/_dashboard-layout/post/$boardSlug/$postSlug"
      path: "/post/$boardSlug/$postSlug"
      fullPath: "/$organizationId/post/$boardSlug/$postSlug"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutPostBoardSlugPostSlugRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/_dashboard-layout/changelog/edit/$changelogSlug": {
      id: "/$organizationId/_dashboard-layout/changelog/edit/$changelogSlug"
      path: "/changelog/edit/$changelogSlug"
      fullPath: "/$organizationId/changelog/edit/$changelogSlug"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutChangelogEditChangelogSlugRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/_dashboard-layout/board/$boardSlug/backlog": {
      id: "/$organizationId/_dashboard-layout/board/$boardSlug/backlog"
      path: "/board/$boardSlug/backlog"
      fullPath: "/$organizationId/board/$boardSlug/backlog"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutBoardBoardSlugBacklogRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
    "/$organizationId/_dashboard-layout/board/$boardSlug/active": {
      id: "/$organizationId/_dashboard-layout/board/$boardSlug/active"
      path: "/board/$boardSlug/active"
      fullPath: "/$organizationId/board/$boardSlug/active"
      preLoaderRoute: typeof OrganizationIdDashboardLayoutBoardBoardSlugActiveRouteImport
      parentRoute: typeof OrganizationIdDashboardLayoutRoute
    }
  }
}

interface OrganizationIdDashboardLayoutRouteChildren {
  OrganizationIdDashboardLayoutRoadmapRoute: typeof OrganizationIdDashboardLayoutRoadmapRoute
  OrganizationIdDashboardLayoutSettingsRoute: typeof OrganizationIdDashboardLayoutSettingsRoute
  OrganizationIdDashboardLayoutIndexRoute: typeof OrganizationIdDashboardLayoutIndexRoute
  OrganizationIdDashboardLayoutChangelogDraftRoute: typeof OrganizationIdDashboardLayoutChangelogDraftRoute
  OrganizationIdDashboardLayoutChangelogPublishedRoute: typeof OrganizationIdDashboardLayoutChangelogPublishedRoute
  OrganizationIdDashboardLayoutFeedbackActiveRoute: typeof OrganizationIdDashboardLayoutFeedbackActiveRoute
  OrganizationIdDashboardLayoutFeedbackBacklogRoute: typeof OrganizationIdDashboardLayoutFeedbackBacklogRoute
  OrganizationIdDashboardLayoutChangelogIndexRoute: typeof OrganizationIdDashboardLayoutChangelogIndexRoute
  OrganizationIdDashboardLayoutFeedbackIndexRoute: typeof OrganizationIdDashboardLayoutFeedbackIndexRoute
  OrganizationIdDashboardLayoutBoardBoardSlugActiveRoute: typeof OrganizationIdDashboardLayoutBoardBoardSlugActiveRoute
  OrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute: typeof OrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute
  OrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute: typeof OrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute
  OrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute: typeof OrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute
  OrganizationIdDashboardLayoutBoardBoardSlugIndexRoute: typeof OrganizationIdDashboardLayoutBoardBoardSlugIndexRoute
}

const OrganizationIdDashboardLayoutRouteChildren: OrganizationIdDashboardLayoutRouteChildren =
  {
    OrganizationIdDashboardLayoutRoadmapRoute:
      OrganizationIdDashboardLayoutRoadmapRoute,
    OrganizationIdDashboardLayoutSettingsRoute:
      OrganizationIdDashboardLayoutSettingsRoute,
    OrganizationIdDashboardLayoutIndexRoute:
      OrganizationIdDashboardLayoutIndexRoute,
    OrganizationIdDashboardLayoutChangelogDraftRoute:
      OrganizationIdDashboardLayoutChangelogDraftRoute,
    OrganizationIdDashboardLayoutChangelogPublishedRoute:
      OrganizationIdDashboardLayoutChangelogPublishedRoute,
    OrganizationIdDashboardLayoutFeedbackActiveRoute:
      OrganizationIdDashboardLayoutFeedbackActiveRoute,
    OrganizationIdDashboardLayoutFeedbackBacklogRoute:
      OrganizationIdDashboardLayoutFeedbackBacklogRoute,
    OrganizationIdDashboardLayoutChangelogIndexRoute:
      OrganizationIdDashboardLayoutChangelogIndexRoute,
    OrganizationIdDashboardLayoutFeedbackIndexRoute:
      OrganizationIdDashboardLayoutFeedbackIndexRoute,
    OrganizationIdDashboardLayoutBoardBoardSlugActiveRoute:
      OrganizationIdDashboardLayoutBoardBoardSlugActiveRoute,
    OrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute:
      OrganizationIdDashboardLayoutBoardBoardSlugBacklogRoute,
    OrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute:
      OrganizationIdDashboardLayoutChangelogEditChangelogSlugRoute,
    OrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute:
      OrganizationIdDashboardLayoutPostBoardSlugPostSlugRoute,
    OrganizationIdDashboardLayoutBoardBoardSlugIndexRoute:
      OrganizationIdDashboardLayoutBoardBoardSlugIndexRoute,
  }

const OrganizationIdDashboardLayoutRouteWithChildren =
  OrganizationIdDashboardLayoutRoute._addFileChildren(
    OrganizationIdDashboardLayoutRouteChildren,
  )

interface OrganizationIdSettingsRouteChildren {
  OrganizationIdSettingsBillingRoute: typeof OrganizationIdSettingsBillingRoute
  OrganizationIdSettingsChangelogPrivacyRoute: typeof OrganizationIdSettingsChangelogPrivacyRoute
  OrganizationIdSettingsChangelogTagsRoute: typeof OrganizationIdSettingsChangelogTagsRoute
  OrganizationIdSettingsCustomizeRoute: typeof OrganizationIdSettingsCustomizeRoute
  OrganizationIdSettingsFeedbackTagsRoute: typeof OrganizationIdSettingsFeedbackTagsRoute
  OrganizationIdSettingsMembersRoute: typeof OrganizationIdSettingsMembersRoute
  OrganizationIdSettingsPreferencesRoute: typeof OrganizationIdSettingsPreferencesRoute
  OrganizationIdSettingsProfileRoute: typeof OrganizationIdSettingsProfileRoute
  OrganizationIdSettingsRoadmapRoute: typeof OrganizationIdSettingsRoadmapRoute
  OrganizationIdSettingsWorkspaceRoute: typeof OrganizationIdSettingsWorkspaceRoute
  OrganizationIdSettingsIndexRoute: typeof OrganizationIdSettingsIndexRoute
}

const OrganizationIdSettingsRouteChildren: OrganizationIdSettingsRouteChildren =
  {
    OrganizationIdSettingsBillingRoute: OrganizationIdSettingsBillingRoute,
    OrganizationIdSettingsChangelogPrivacyRoute:
      OrganizationIdSettingsChangelogPrivacyRoute,
    OrganizationIdSettingsChangelogTagsRoute:
      OrganizationIdSettingsChangelogTagsRoute,
    OrganizationIdSettingsCustomizeRoute: OrganizationIdSettingsCustomizeRoute,
    OrganizationIdSettingsFeedbackTagsRoute:
      OrganizationIdSettingsFeedbackTagsRoute,
    OrganizationIdSettingsMembersRoute: OrganizationIdSettingsMembersRoute,
    OrganizationIdSettingsPreferencesRoute:
      OrganizationIdSettingsPreferencesRoute,
    OrganizationIdSettingsProfileRoute: OrganizationIdSettingsProfileRoute,
    OrganizationIdSettingsRoadmapRoute: OrganizationIdSettingsRoadmapRoute,
    OrganizationIdSettingsWorkspaceRoute: OrganizationIdSettingsWorkspaceRoute,
    OrganizationIdSettingsIndexRoute: OrganizationIdSettingsIndexRoute,
  }

const OrganizationIdSettingsRouteWithChildren =
  OrganizationIdSettingsRoute._addFileChildren(
    OrganizationIdSettingsRouteChildren,
  )

interface OrganizationIdRouteChildren {
  OrganizationIdDashboardLayoutRoute: typeof OrganizationIdDashboardLayoutRouteWithChildren
  OrganizationIdSettingsRoute: typeof OrganizationIdSettingsRouteWithChildren
}

const OrganizationIdRouteChildren: OrganizationIdRouteChildren = {
  OrganizationIdDashboardLayoutRoute:
    OrganizationIdDashboardLayoutRouteWithChildren,
  OrganizationIdSettingsRoute: OrganizationIdSettingsRouteWithChildren,
}

const OrganizationIdRouteWithChildren = OrganizationIdRoute._addFileChildren(
  OrganizationIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  OrganizationIdRoute: OrganizationIdRouteWithChildren,
  EmailVerifyRoute: EmailVerifyRoute,
  RegisterRoute: RegisterRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
