/**
 * Dev-only seed authentication helper.
 *
 * `@feeblo/auth` depends on `@feeblo/db`, so importing it from the seed
 * script creates a package cycle (`db -> auth -> db`). Seeding only needs
 * `signUpEmail` to create password users with correctly-hashed credentials,
 * so this module builds a stripped-down Better Auth instance (email+password
 * only, no organization/polar/captcha plugins) backed by its own postgres-js
 * connection.
 *
 * Do not import this outside dev scripts (`seed.ts`). The seed entrypoint
 * owns environment reads and randomness; this module only parses the former
 * and receives the latter as an explicit option.
 */
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { drizzle } from "drizzle-orm/postgres-js";
import * as Data from "effect/Data";
import postgres from "postgres";

import { relations } from "./src/relations";
import {
  accountTable,
  sessionTable,
  userTable,
  verificationTable,
} from "./src/schema";

/** Environment-derived seed configuration (everything except the secret). */
export type SeedAuthConfig = {
  /** Postgres connection string for a real server (PGlite is unsupported). */
  readonly databaseUrl: string;
  /** Base URL handed to Better Auth; unused by seeding beyond construction. */
  readonly baseUrl: string;
};

/** Validated inputs for building the seed-only Better Auth instance. */
export type SeedAuthOptions = SeedAuthConfig & {
  /**
   * Ephemeral per-run secret generated by the seed entrypoint. Seeding writes
   * only scrypt-hashed credentials (which never involve the secret) and never
   * issues sessions, so the app secret is unnecessary — and reusing the short
   * dev secret trips Better Auth's weak-secret warnings on every run.
   */
  readonly secret: string;
};

/** Known seed-configuration failure; the seed entrypoint reports it and exits. */
export class SeedConfigError extends Data.TaggedError("SeedConfigError")<{
  readonly message: string;
}> {}

/**
 * Parse seed configuration from raw environment values.
 *
 * @param env - Untrusted environment mapping from the seed entrypoint.
 * @returns Validated configuration, or a `SeedConfigError` describing the
 * first problem. Malformed URLs beyond these checks surface from the
 * postgres driver through the seed boundary.
 */
export const parseSeedAuthOptions = (
  env: Record<string, string | undefined>
): SeedAuthConfig | SeedConfigError => {
  const databaseUrl = env.DATABASE_URL;
  if (!databaseUrl) {
    return new SeedConfigError({
      message:
        "SeedConfigError: DATABASE_URL is required to seed the database.",
    });
  }
  if (
    databaseUrl.startsWith("pglite:") ||
    databaseUrl.startsWith("memory://")
  ) {
    return new SeedConfigError({
      message:
        "SeedConfigError: db:seed requires a real Postgres DATABASE_URL (PGlite is not supported).",
    });
  }
  return {
    databaseUrl,
    baseUrl: env.API_URL ?? env.APP_URL ?? "http://localhost:3000",
  };
};

/** Sign-up result shape seeding relies on. */
export type SeedSignUpResult = {
  readonly user: {
    readonly id: string;
    readonly email: string;
    readonly name: string;
  };
};

/**
 * Narrow Better Auth surface used by seeding. Kept narrow so this module
 * does not couple to `betterAuth`'s per-options generic.
 */
export type SeedAuth = {
  readonly api: {
    readonly signUpEmail: (args: {
      readonly body: {
        readonly email: string;
        readonly password: string;
        readonly name: string;
      };
    }) => Promise<SeedSignUpResult | null>;
  };
};

/** Seed auth instance with its explicit release. */
export type SeedAuthHandle = {
  /** Better Auth instance for creating seed users. */
  readonly auth: SeedAuth;
  /** Close the backing postgres connection. */
  readonly close: () => Promise<void>;
};

/**
 * Build the seed-only Better Auth instance.
 *
 * @param options - Validated configuration with an entrypoint-owned secret.
 * @returns The auth instance with its connection release.
 */
export const createSeedAuth = (options: SeedAuthOptions): SeedAuthHandle => {
  const sql = postgres(options.databaseUrl, { max: 1 });
  const db = drizzle({ client: sql, relations });

  // SAFETY: better-auth infers a per-options generic (`Auth<typeof options>`)
  // that is invariant and cannot be named from the outside; the cast narrows
  // it to the `signUpEmail` subset seeding actually calls, and seed.ts
  // validates the returned `user` before using it.
  const auth = betterAuth({
    database: drizzleAdapter(db, {
      provider: "pg",
      schema: {
        user: userTable,
        session: sessionTable,
        account: accountTable,
        verification: verificationTable,
      },
    }),
    secret: options.secret,
    baseURL: options.baseUrl,
    telemetry: { enabled: false },
    emailAndPassword: {
      enabled: true,
      requireEmailVerification: false,
      autoSignIn: false,
    },
  }) as SeedAuth;

  return {
    auth,
    close: () => sql.end(),
  };
};
